- src/scripts/modules/media/header/header-template.html
- src/scripts/modules/media/tabs/tools/tools-template.html
- src/scripts/modules/media/title/title-template.html
- src/scripts/modules/workspace/results/list/list-template.html
> Update 'Derive' copy to be clearer

- src/scripts/models/content.coffee
- src/scripts/modules/media/editbar/block-publish/modals/block-publish-template.html
- src/scripts/modules/media/editbar/block-publish/modals/block-publish.coffee
- src/scripts/modules/media/editbar/editbar-template.html
- src/scripts/modules/media/editbar/editbar.coffee
Depends on https://github.com/Connexions/cnx-authoring/issues/173
> Block publishing

- src/scripts/modules/role-acceptances/role-acceptances-template.html
- src/scripts/modules/role-acceptances/role-acceptances.coffee
Fixes https://github.com/Connexions/webview/issues/839
> Disabling submit button unless all roles are accepted or rejected

- src/scripts/helpers/handlebars/author.coffee
Fixes https://github.com/Connexions/webview/issues/867
> Checking for undefined in author.coffee

- src/styles/main.less
Fixes https://github.com/Connexions/webview/issues/863
> Overwriting bootstrap modal css style

- src/scripts/models/content.coffee
- src/scripts/modules/media/editbar/block-publish/modals/block-publish.coffee
This code checks to see if book is publishable, content in book is publishable and if individual pages are publishable. Tested with published pages, draft pages and books.
> Publish blockers fix for published content

- src/scripts/modules/workspace/popovers/new/modals/new-media.coffee
this solves #872, and is a step towards solving #870
> navigate to newly created content

- src/scripts/helpers/links.coffee
- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/tabs/tabs.coffee
- src/scripts/modules/workspace/popovers/new/modals/new-media.coffee
- src/scripts/pages/contents/contents.coffee
- src/scripts/router.coffee
> Open new book with the TOC already open

- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/tabs/tabs.coffee
- src/scripts/router.coffee
> Preserve book titles

- src/scripts/modules/media/media.coffee
> keep the query string on rewrite of url

- src/scripts/helpers/backbone/history.coffee
- src/scripts/modules/media/tabs/contents/toc/page.coffee
Fixes https://github.com/Connexions/webview/issues/882
> Removing extra content stack from history when navigating to a book

- bower.json
- src/scripts/config.js
- src/scripts/helpers/backbone/views/editable.coffee
> Upgrade aloha, lodash, font-awesome and mocha

- src/scripts/modules/media/body/body.less
> Don't set media-body to 10000px width

- src/scripts/models/contents/collection.coffee
> Support page lookup by model

- src/scripts/modules/media/tabs/metadata/metadata.less
> Match select2 styling for summary box

- src/scripts/modules/media/body/content.less
> Remove CSS numbering from footnotes

- src/scripts/modules/media/title/title.coffee
> Make the appropriate title element editable

- src/scripts/config.js
Most notable improvement:
`Speed improvements. The HTML-CSS output performance was improved by 30-40% (depending on content complexity, with higher gains in more complex content such as very long documents).`
> Upgrade to MathJax 2.5

- src/scripts/modules/media/body/body-template.html
- src/scripts/modules/media/body/body.coffee
> Show progress bar when page is loading

- package.json
Avoid having prompts when installing or upgrading webview from a script
> Add config.analytics=false to bower install / upgrade

- src/scripts/modules/media/editbar/modals/list/section.coffee
- src/scripts/modules/media/editbar/modals/publish.coffee
Fixes https://github.com/Connexions/webview/issues/874
> Update book title in publish modal

- src/scripts/modules/media/tabs/metadata/metadata.less
Fixes https://github.com/Connexions/webview/issues/930
> Set summary border on attribute

- src/scripts/config.js
Fixes https://github.com/Connexions/webview/issues/935
> User friendly ZenDesk form

- src/scripts/modules/media/editbar/modals/list/section.coffee
Fixes https://github.com/Connexions/webview/issues/936
> Render contents when section is derived

- src/scripts/modules/media/body/body.less
Fixes https://github.com/Connexions/webview/issues/937
Fixes https://github.com/Connexions/webview/issues/709
> Remove duplication of label with title

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/tabs/tools/tools.coffee
> Retain teacher edition state between pages

- src/scripts/helpers/backbone/views/editable.coffee
Fixes part of https://github.com/Connexions/webview/issues/910
The other part of the fix can be found here https://github.com/oerpub/Aloha-Editor/pull/200
> Make sure that all unwrapped text is wrapped in '<p></p>'

- src/scripts/modules/media/body/content.less
Fixes https://github.com/Connexions/webview/issues/992
> Fix ordered list display in content

- src/scripts/modules/media/body/body.less
Fixes https://github.com/Connexions/webview/issues/998
> Hide cnx-pi content

- src/scripts/collections/featured-books.coffee
- src/scripts/collections/subjects.coffee
- src/scripts/models/contents/node.coffee
- src/scripts/models/role-acceptances.coffee
- src/scripts/models/search-results.coffee
- src/scripts/modules/media/editbar/modals/publish.coffee
- src/scripts/modules/media/tabs/metadata/metadata.coffee
- src/scripts/modules/role-acceptances/role-acceptances.coffee
- src/scripts/modules/workspace/popovers/delete/modals/delete.coffee
- src/scripts/session.coffee
slightly ugly and cryptic, but it works.
> make port optional

- src/scripts/configs/aloha.coffee
- src/scripts/modules/media/editbar/editbar-template.html
Depends on https://github.com/oerpub/Aloha-Editor/pull/213
> Removed simulation plugin for now

- src/scripts/modules/media/body/body.coffee
> Only trigger the toggle event once in exercises

- src/scripts/modules/media/tabs/metadata/metadata-template.html
- src/scripts/modules/media/tabs/metadata/metadata.coffee
Fixes https://github.com/Connexions/webview/issues/1015
> Fix values for print styles

- src/scripts/configs/embeddables.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/embeddables/exercise-template.html
- src/scripts/modules/media/body/embeddables/iframe-template.html
- src/scripts/modules/media/body/embeddables/terps-template.html
- src/scripts/settings.js
Should work with:
* [Concept coach](http://localhost:8000/contents/bf516ea9-7e9c-484d-ba16-6bb73314f38b@3.3:6/Concept_Coach_Test_Collection)
* [exercises](http://localhost:8000/contents/092bbf0d-0729-42ce-87a6-fd96fd87a083@4/Force)
need to check with @Dantemss about https://exercises-dev1.openstax.org/ allow access from final destination of production
> adding it in embeddable exercises code from feature to production

- src/scripts/configs/aloha.coffee
- src/scripts/modules/media/editbar/editbar-template.html
Depends on https://github.com/oerpub/Aloha-Editor/pull/216
> Media plugin for Aloha

- src/scripts/configs/aloha.coffee
Part of fix for https://github.com/Connexions/webview/issues/924
> Add enableTypes to example

- src/scripts/models/site-status.coffee
- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.less
Cherrypick site status messaging to production
> [production] Messaging

- src/scripts/modules/header/header.coffee
The missing changes for production.
> Move changes for messages to production

- src/scripts/collections/site-status.coffee
- src/scripts/models/site-status.coffee
- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.coffee
- src/scripts/modules/header/site-status/site-status-template.html
- src/scripts/modules/header/site-status/site-status.coffee
Removed site status code from header.coffee and put it in it's own view, added site status to collection, added code to set cookies when alerts are dismissed, and some refactoring in templates and views.
> Dismissible alerts

- src/scripts/modules/header/header-template.html
- src/styles/main.less
moved form on legacy some time ago to slow down spammers
> [production] Legacy new account link

- src/scripts/modules/media/body/embeddables/exercise-template.html
> [Production] show only first item from exercises api, otherwise, show blank

- src/scripts/helpers/backbone/views/base.coffee
- src/scripts/settings.js
- test/scripts/helpers/backbone/views/base.js
Also, in settings.js 'titlePrefix' is now 'titleSuffix', w/ value changed accordingly.
> Changed title order for OES, adjusted relevant test

- src/scripts/modules/media/body/content.less
> max-width for all images, esp. outside figures

- src/scripts/helpers/links.coffee
- src/scripts/modules/media/media.coffee
- test/scripts/helpers/links.js
And adjusted existing tests to match new layout
> Replaced book title with page title in URL

- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/media.coffee
- test/scripts/modules/media/header/header.js
Title now includes the title of the individual page being displayed (as well as the book name).  Includes tests
> Changed page title in books

- src/scripts/helpers/handlebars/trim.coffee
- src/scripts/settings.js
- test/scripts/helpers/handlebars/trim.js
- test/scripts/helpers/links.js
> Changed underscores in url to dashes

- bower.json
- package.json
- src/scripts/config.js
> Update dependencies for production

- src/scripts/modules/media/editbar/editbar-template.html
https://github.com/Connexions/webview/issues/1118
https://github.com/oerpub/Aloha-Editor/pull/219
> Change labels in format dropdown

- src/scripts/helpers/backbone/views/base.coffee
- src/scripts/helpers/handlebars/trim.coffee
- src/scripts/helpers/links.coffee
- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/media.coffee
- src/scripts/modules/search/results/list/item-partial.html
- test/scripts/helpers/links.js
Changed URL (in production) of books to have the page title at the end, instead of the book title
> Changed Url to include page title [production]

- src/scripts/modules/media/editbar/editbar-template.html
- src/scripts/modules/media/editbar/editbar.less
https://github.com/oerpub/Aloha-Editor/pull/220
> Format dropdown selection fix

- src/scripts/modules/header/header.less
- src/scripts/modules/search/results/filter/filter-template.html
- src/scripts/modules/search/results/filter/filter.coffee
- src/scripts/modules/search/results/filter/filter.less
- src/scripts/modules/search/results/list/item-partial.html
- src/scripts/modules/search/results/list/pagination-partial.html
> Improve accessibility on search page

- src/styles/aloha-hacks.less
This PR also needs to be merged. https://github.com/oerpub/Aloha-Editor/pull/224
> Capitalize title in notes dropdown in editor

- Gruntfile.coffee
- src/scripts/modules/footer/footer-template.html
- src/scripts/pages/license/license-template.html
- src/scripts/pages/license/license.coffee
- src/scripts/pages/license/license.less
- src/scripts/router.coffee
Fixed Licensing link text in footer
> New license

- src/scripts/modules/header/header.less
Update CSS to set opacity to 0 when not in focus
> Hide "Skip to Main Content" using opacity CSS

- src/scripts/modules/featured-books/featured-books.less
- src/scripts/modules/media/body/body.less
- src/scripts/modules/media/body/content.less
- src/scripts/modules/media/footer/footer.less
When viewed in portrait mode on mobile
> Fix padding in featured books more links and notes in content 

- .gitignore
- src/scripts/modules/footer/footer-template.html
- src/scripts/modules/footer/footer.less
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/footer/footer-template.html
- src/scripts/modules/media/footer/footer.coffee
- src/scripts/modules/media/footer/footer.less
- src/scripts/modules/media/footer/inherits/tab/tab.coffee
- src/scripts/modules/media/footer/inherits/tab/toggle-partial.html
- src/scripts/modules/media/header/header-template.html
- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/header/header.less
- src/scripts/modules/media/tabs/metadata/metadata.less
- src/scripts/modules/media/title/title.less
- src/scripts/modules/search/results/breadcrumbs/breadcrumbs-template.html
- src/scripts/modules/search/results/breadcrumbs/breadcrumbs.coffee
- src/scripts/modules/search/results/breadcrumbs/breadcrumbs.less
- src/scripts/pages/app/modals/legacy.coffee
- src/scripts/pages/app/modals/legacy.less
Links and buttons participate in tab order. Some had no styling change when they got focus, so I applied stylings, trying to keep them minimal.
> Accessibility shortcuts

- src/scripts/modules/footer/footer-template.html
- src/scripts/modules/header/header-template.html
Relabel Content as Search
Remove News link
> Content and News link updates

- src/scripts/models/contents/node.coffee
Exclude zero-size files and files in EPUB format.
> Epub links

- src/scripts/pages/donate/donation-slider/donation-slider-template.html
- src/scripts/pages/donate/donation-slider/donation-slider.coffee
Added aria value attributes for donation slider, made aria-valuenow
update as the slider changed, and turned a couple magic numbers into
variables.
> Aria attributes for donation slider

- src/scripts/helpers/links.coffee
- src/scripts/router.coffee
Nav links put page uuids in URLs
Router handles URLs with page uuids (as well as page numbers)
> Handle page uuids

- src/scripts/pages/contents/contents.coffee
- src/scripts/pages/search/search.coffee
Removed MinimalFooter, which was just a copy of Footer
> Changes that were not included with minimal view

- src/scripts/modules/minimal/media/header/header-template.html
- src/scripts/modules/minimal/media/header/header.less
- src/scripts/modules/minimal/media/title/title-template.html
- src/scripts/modules/minimal/media/title/title.less
Moved alignment to .less files, center on small screens only
> Center on small screens only

- src/scripts/helpers/links.coffee
- src/scripts/models/contents/collection.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/router.coffee
URLs display using short id’s instead of uuids for both book and page.
> Handle short id addresses

- src/scripts/modules/header/header-template.html
- src/scripts/modules/media/editbar/modals/publish-template.html
- src/scripts/modules/media/tabs/metadata/metadata-template.html
- src/scripts/modules/media/tabs/metadata/metadata.coffee
Spent some time cross-training on webview. Now prettier. @dak what do you think of bootstrap tooltip for this case?
> display changed license in authoring

- src/scripts/modules/media/title/title.coffee
normalizing header levels broke editable for title
> make title editable again

- src/scripts/modules/media/body/body.coffee
canonicalizePath handles book-pages and individual pages now, and body
listens for changes to shortId to call canonicalizePath
> Short ids for pages

- src/scripts/modules/media/nav/nav-template.html
Fixes #1240
Thought this fix was in an earlier branch, but nope.
> No Contents button on bottom nav bar

- src/scripts/modules/media/header/header.less
- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/window-with-sidebar/window-with-sidebar.less
Fixes #1241
Fixes #1242
On small screens, when TOC is open, navigating to another page will close TOC and scroll to top of content.
> Dev toc fixes

- src/scripts/modules/find-content/find-content-template.html
- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.coffee
- src/scripts/modules/header/header.less
- src/scripts/modules/media/nav/nav-template.html
- src/scripts/modules/media/nav/nav.less
- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/pages/about/about-template.html
- src/scripts/pages/donate/donation-slider/donation-slider-template.html
- src/scripts/pages/donate/form/form-template.html
Added/changed tabindex attributes to ensure that the most useful features are first in the tab sequence.
Replaced Donate button with Give menu item
Skip to Content removed because it can't work with the new layout, and tabindex changes work better
Highlighted Contents button on focus
> Accessibility

- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.coffee
Show search result total at top of TOC.
When search results in no matches, hide all TOC entries.
> Provide feedback on zero, one, multiple matches

- src/scripts/modules/media/tabs/contents/toc/page.coffee
- src/scripts/modules/media/tabs/contents/toc/section.coffee
Browser history was getting the wrong pages for pages clicked in the TOC.
> Navigate router before setting page

- src/scripts/modules/media/editbar/modals/list/page.less
- src/scripts/modules/media/footer/footer-template.html
- src/scripts/modules/media/header/header.less
- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/contents.less
- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/page.coffee
- src/scripts/modules/media/tabs/contents/toc/page.less
- src/scripts/modules/media/tabs/contents/toc/section.coffee
- src/scripts/modules/media/tabs/contents/toc/section.less
- src/scripts/modules/media/title/title.less
- src/styles/variables.less
Multiple UX and cosmetic changes
Trello card:
https://trello.com/c/AgU4BF3W/1502-table-of-contents-changes
> Toc changes 1

- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/toc/page.less
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/modules/media/tabs/contents/toc/section.coffee
- src/scripts/modules/media/tabs/contents/toc/section.less
Hover colors help indicate whether you’re navigating or just toggling.
Arrows toggle; chapter/titles navigate to introduction page and ensure
the section is open.
> TOC interim solution

- Gruntfile.coffee
need this to nagivate to /browse on a dist deploy
> browse path

- bower.json
- src/scripts/config.js
- src/scripts/settings.js
- src/styles/main.less
different behavior for dist vs local, fixed and should work both ways...hopefully.  Works locally when `npm run dist`
> fix css non-loading through less loader

- src/scripts/modules/find-content/find-content-template.html
- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.coffee
- src/scripts/modules/header/header.less
- src/scripts/modules/media/nav/nav-template.html
- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/pages/about/about-template.html
- src/scripts/pages/donate/donation-slider/donation-slider-template.html
- src/scripts/pages/donate/form/form-template.html
Restore "skip to main content" hidden button and remove tabindex overrides.
Reverts changes made in #1253 
Fixes #1269
> Revert accessibility changes

- src/scripts/modules/header/header.less
- src/scripts/modules/media/body/body-template.html
- src/scripts/modules/media/body/body.less
- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/title/title.coffee
- src/scripts/modules/window-with-sidebar/window-with-sidebar.less
Skip to header was messing things up. Absolute-positioning its div fixed that.
See commits for other bug fix descriptions.
> Fix pinned header problems

- bower.json
- src/scripts/config.js
- src/scripts/modules/media/body/body.coffee
> Various concept coach fixes

- src/scripts/modules/media/tabs/contents/contents.coffee
> Doomsday fixes 1

- src/scripts/modules/media/body/body.coffee
links from CC back to book works nicely now
> look up page by uuid to link to it

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/media.coffee
- src/scripts/pages/app/app.coffee
Doing a little clean up in the mean time
* handle link to books too in body cc book nav
* pull bare window events into app where throttled backbone triggers optimized event
> fix the cc to book linking

- bower.json
cc now uses jquery for ajax and doesnt build underscore into itself
> attempt to fix CC in IE by taking out Promises dependent ajax lib

- bower.json
Fix the bug so that it scrolls to CC on cc open
> IE was scrolling to the top on cc open

- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.coffee
Target was '#main', which is no longer correct. Revised code a bit.
> Fix skip to content

- src/scripts/helpers/links.coffee
- src/scripts/models/contents/node.coffee
- test/scripts/helpers/links.js
Ross would have liked to have this yesterday.
> Add a getShortUuid method to avoid Problems™

- src/scripts/modules/media/media.coffee
Leftover resize/scroll callbacks were firing when the view was gone,
causing some undefined errors.
> Remove resize/scroll callbacks when the view closes

- src/scripts/loader.coffee
- src/scripts/modules/header/header.coffee
- src/scripts/session.coffee
Attempt to load profile once per page
> Stop polling profile

- src/scripts/modules/header/header.coffee
If user goes to another tab or window or application and comes back.
> Poll for user profile on window focus

- src/scripts/models/content.coffee
- src/scripts/models/contents/collection.coffee
- src/scripts/models/contents/node.coffee
- src/scripts/modules/media/body/body.coffee
Rewrote page lookup so it finds page uuids without version. Had it set error to 404 if page is not found.
> Fix uuid redirection

- bower.json
- src/scripts/configs/embeddables.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/body.less
Also related to openstax/concept-coach#53 Mathsss
> changes for the new cc launcher with fixed cc-modal

- src/scripts/router.coffee
> Decoded path replaces encoded path in history

- src/scripts/modules/media/media.less
So the TOC doesn't resize smaller on pinning when the contents are narrow-ish.
> Fix toc width

- src/styles/main.less
> Fix Zendesk button text display in IE11

- src/scripts/config.js
- src/scripts/modules/media/body/body.coffee
trying to debug something in cc
> update the config to load in dev version of cc with full react exceptions

- bower.json
- src/scripts/config.js
- src/scripts/modules/media/body/body.coffee
where launcher and modal are same react component and the launcher get's unmounted when webview navs
> update to cc version

- bower.json
- src/scripts/modules/media/body/body.coffee
also, don't stop modal from opening since component will have been mounted from the start
> render launcher only actually when there have been exercises to hide

- bower.json
updates coach with teacher fix for testing
> update coach with teacher fix for testing

- bower.json
also, , re-synced cc dist with master
> update coach with language update for teacher registration

- bower.json
- src/scripts/helpers/links.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/embeddables/cc-launcher-template.html
- src/scripts/modules/media/body/embeddables/coach.coffee
Cleans up `body.coffee` and makes use of `regions`
Branched off of #1334 so that should be merged first before merging this.  The remaining commit off of #1334 will be https://github.com/Connexions/webview/commit/98e63aff162dbce60c20a7f5449a7c91079a30d1
> coach as separate view/region

- src/scripts/models/contents/collection.coffee
It looks like the problem of adding pages on dev may be this single
typo.
> Fix add-page problem

- src/scripts/models/contents/collection.coffee
- src/scripts/modules/media/footer/metadata/metadata.coffee
- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/toc/section.coffee
Tests and short-circuits for some null conditions
Also updates page numbering as you change TOC
Still requires saving draft and coming back to book to edit new pages
Fixes #1341
> Fixes errors when adding new, published pages to book

- src/scripts/modules/minimal/search/advanced/advanced.coffee
- src/scripts/modules/search/advanced/advanced.coffee
URI encode search terms so that question marks and such work
Fixes #1343
> Encode query terms

- bower.json
Bug is apparent when registering for a CC course after navigating around a few pages webview.
> Update CC with fix for undefined @courses on user/model

- bower.json
See https://github.com/openstax/react-components/pull/36/files for code changed
> update coach with checked answers fixed and showing for each question in review mode

- bower.json
> update coach with fix for enroll vs login

- bower.json
1. Progress page fix
openstax/concept-coach#108
1. Checked answers for question in review
openstax/concept-coach#113
1. Enroll/login
openstax/concept-coach#115
1. zendesk url and error notification improvements
openstax/concept-coach#116
1. multiple choice only questions
openstax/concept-coach#117
> update coach with the following fixes:

- bower.json
- src/scripts/modules/media/body/body.less
See notes in: https://github.com/openstax/concept-coach/releases/tag/d-2016-01-20-c
> update to coach latest release

- bower.json
PR against production, to avoid rebase/merge
> revert concept coach to current released production version [production PR]

- src/scripts/modules/media/body/content.less
> Center figure labels under images

- bower.json
- src/scripts/modules/media/body/body.less
- src/scripts/modules/media/body/embeddables/coach.coffee
pass in next page label to coach and set up to listen for next, clean up book nav from coach function
Updates coach to [release d-20160128.a](https://github.com/openstax/concept-coach/releases/tag/d-20160128.a)
> hint at a next step after coach last question

- src/scripts/modules/media/header/popovers/book/book-template.html
- src/scripts/modules/media/header/popovers/book/book.coffee
- src/scripts/pages/donate/donation-slider/donation-slider-template.html
- src/scripts/pages/donate/donation-slider/donation-slider.coffee
Detect iPad, mark download link with data-ipad
Click on data-ipad link forces window navigation
Download testing is hard to verify.
> Fix iPad download issue

- src/scripts/models/contents/collection.coffee
- src/scripts/modules/media/body/body.coffee
* be stricter about what links to parse in body
* make sure id is valid before trying to get page
Worked with @RoyEJohnson
> fix links being mis-modified

- src/scripts/models/contents/collection.coffee
- src/scripts/modules/media/body/body.coffee
See also #1369 
* be stricter about what links to parse in body
* make sure id is valid before trying to get page
Worked with @RoyEJohnson
> Fix the page link issue

- bower.json
* Remember free response when switching between exercises
* Screen to update student identifier
> Update CC build with latest fixes

- bower.json
- src/scripts/config.js
- src/scripts/modules/media/body/embeddables/coach.coffee
> ask us now works with coach open

- bower.json
* update student ID workflow
* Exercise trouble link
* free response recall
> ConceptCoach: Add trouble link, student ID workflow, free response recall

- src/scripts/modules/media/media.coffee
Clicking a hash link did not trigger the adjustment if it was the same
hash as was loaded in the URL.
> Fix scroll to same hash

- bower.json
Updating coach to this release with student id in edit student id -- [d-20160309.a](https://github.com/openstax/concept-coach/releases/tag/d-20160309.a)
> update coach to the latest with student id in edit student id feature

- src/scripts/modules/media/header/header.coffee
regarding issue: https://github.com/openstax/sustain/issues/5
> CNX Summary Widget bug -- Can't leave open and cut and paste text

- bower.json
Changes student id update screen's cancel button to be a plain blue link
> Update released ConceptCoach version

- bower.json
This updates the concept coach version for hotfix.
> Updates concept coach

- bower.json
Reverts Connexions/webview#1398
> Revert "Updates concept coach"

- bower.json
Creating a new PR since it looks like https://github.com/Connexions/webview/pull/1398 isn't getting updated.
> Updating concept coach to d-20160321.b

- bower.json
Includes fixes from react-components for FR continue button, multiple choice sorting, and update with systems notifications feature. see [release notes](https://github.com/openstax/concept-coach/releases/tag/d-20160323.a) for full details
> update with latest coach

- src/scripts/modules/media/footer/footer.coffee
- src/scripts/modules/media/latest/latest.coffee
Fixed latest.coffee so that when the url to the new version is clicked from minimal view, it will maintain the minimal view in the new window.
> Fix/ keep minimal in new version url

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/header/header-template.html
- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/header/header.less
- src/scripts/modules/media/media.coffee
> Add Jump to Concept Coach button

- src/scripts/modules/media/body/content.less
Changed content.less so that the numbering shows up for the Review and Discussion questions at the end of the module.
> Fixes the issue of numbering for questions not showing up

- src/scripts/modules/media/body/body.less
the dist version's background image is not styled, this will fix this
> background image css needs to be more specific

- bower.json
- src/scripts/modules/media/body/body.less
> more space for coach sign up button, white steam, no double underline for coach links

- bower.json
update the concept coach to the [latest](https://github.com/openstax/concept-coach/releases/tag/d-20160628.a)
JK not ready yet
> update coach to latest with sign up styling and launch coach button text

- bower.json
Updates to this CC [version](https://github.com/openstax/concept-coach/releases/tag/d-20160711.a).  Should fix some CC issues, i.e. the [double answer for multiple choice questions bug](https://www.pivotaltracker.com/story/show/126066679)
> update to latest coach with the latest react-components fixes

- bower.json
updates to coach [details here](https://github.com/openstax/concept-coach/releases/tag/d-20160718.a) including:
* 🐛 email confirmation fix
* error notification support link update
* 🐛 space practice tooltip
* 💄 confirm join width
* "course/period" to "section"
> update coach to latest with email confirm fix, support link update, and others

- bower.json
following now links to [force help link for cc](http://openstax.force.com/support?l=en_US&c=Products%3AConcept_Coach)
> quick patch with openstax/concept-coach#158

- src/scripts/modules/media/body/body.less
Reverts Connexions/webview#1438
> Revert "override list styles for coach so that they have single numbers"

- bower.json
for concept coach
updates to this [version](https://github.com/openstax/concept-coach/releases/tag/d-20160801.a) of coach
> update with change section text and related section for exercise

- bower.json
Updates coach to [latest](https://github.com/openstax/tutor-js/releases/tag/coach-20160816.a) to prevent:
> coach in IE is missing promise polyfill

- bower.json
includes coach closing logout fix and user menu remove focus styling fix
coach updated to [coach-20160909.a ](https://github.com/openstax/tutor-js/releases/tag/coach-20160909.a)
> update coach to latest release

- bower.json
Fixes bugs with the error dialog's details button and stops double
submission of answers
> Update CC 

- src/scripts/modules/media/body/body.coffee
as opposed to before quizzes, which dont always exist on every non-intro page
https://trello.com/c/qRpCZ6dV
> coach should mount after summary

- bower.json
- src/scripts/modules/media/body/body.less
updates coach to intro cards release: https://github.com/openstax/tutor-js/releases/tag/coach-20160923.a
> update coach with intro cards and intro cards styling

- src/scripts/modules/media/body/body.less
> style fix for coach

- bower.json
Updates coach to [version with some accessibility improvements](https://github.com/openstax/tutor-js/releases/tag/coach-20160927.a), especially around question answering.
> update coach with version of more accessibility support

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/embeddables/exercise-template.html
This is missing any  styling, or classes as hooks for styling, but works o.k.
All the questions on this page are acutally multiple choice:
http://cnx.org/contents/bDIuMp-w@1.1:XwiMLb76@2/Synthesis-of-Biological-Macrom
> render the choices for multiple-choice questions, as well

- bower.json
coach update with [true-false fix](https://github.com/openstax/tutor-js/releases/tag/coach-20161031.a), based off of d89d8e5, `v0.21.0` from master
> coach needs a hot-fix for true-false questions

- bower.json
A followup to #1468, which had an incorrect build.  This one **hopefully** contains the fixed commits
> Update ConceptCoach to fix true-false format bug

- bower.json
pulls in latest [coach updates](https://github.com/openstax/tutor-js/releases/tag/coach-20161221.a)
needs #1476 to not fail travis
> update coach to latest

- bower.json
Update CC:
* Fixes deprecated & removed isMounted calls
* Removes the alternative courses listing
* Stacks notifications so they're all visible
> Update CC to 20170103

- bower.json
this updates coach to [this release](https://github.com/openstax/tutor-js/releases/tag/coach-20170111.a) which fixes: openstax/tutor-js#1560 and openstax/tutor-js#1561
> update coach with fix for multiple courses on same book

- bower.json
openstax/tutor-js#1564 is needed as well for 2nd semester fix.
> coach adjustments for handling 2nd semester

- bower.json
updates coach to [coach-20170117.a](https://github.com/openstax/tutor-js/releases/tag/coach-20170117.a)
> update with coach 2nd semester flow adjustments

- bower.json
- package.json
updates coach to [coach-20170119.a](https://github.com/openstax/tutor-js/releases/tag/coach-20170119.a)
> Update coach 2nd sem enrollment

- src/scripts/pages/about/contact/contact-template.html
Changed support email address
Merges #1472 fix into master.
> Changed support email address

- bower.json
updates coach to [release with sign up as student auto-select](https://github.com/openstax/tutor-js/releases/tag/coach-20170208.a)
> update coach to version with updated sign up as student auto-select

- bower.json
- package.json
update coach to [coach-20170223.a](https://github.com/openstax/tutor-js/releases/tag/coach-20170223.a)
> Update coach smaller with sign up fix

- src/scripts/config.js
ports fix over from hotfix #1504
> fix require js compile time for coach in build

- bower.json
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/embeddables/coach.coffee
and require underscore in body and coach just in case
[coach-20170223.b](https://github.com/openstax/tutor-js/releases/tag/coach-20170223.b)
> update to coach build without global lodash

- bower.json
errata form url is retrieved from the server side
> update coach with errata form url

- Gruntfile.coffee
- src/index.html
- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/config.js
- src/scripts/helpers/backbone/views/base.coffee
- src/scripts/pages/error/error.coffee
* fix error page not rendering
* due to `pageTitleArgs` being present and `title` element being [overwritten](https://github.com/Connexions/webview/compare/update-int-loading?expand=1#diff-12f9905355b57f9d843a0613d4f8dee4L85)
* fix page title suffixing
* use require js for babel polyfill loading
> Update int loading

- src/scripts/modules/media/body/content-baked.less
addressing this issue 
https://github.com/Connexions/cnx-rulesets/issues/226
I couldn't find a place that this broke anything.
> remove (unneeded?) padding from exercise

- src/scripts/modules/media/body/content-baked.less
fixes issue [#211](https://github.com/Connexions/cnx-recipes/issues/211)
> fix #211 Answer Key: solutions are on their own lines

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
Long ago I fixed the footer problem incorrectly, therefore I refixed it.
> Refix the footer problem

- bower.json
Fixes #1553 . Please let QA merge this one 😄
> pin the l20n version

- bower.json
- src/scripts/config.js
updating packages to the most recent versions, except alpha/beta versions.
running all the unit tests and running webview locally worked with no other changes made.
> Updating javascript packages

- src/scripts/modules/media/body/content-baked.less
fixes https://github.com/Connexions/cnx-recipes/issues/226
> remove extra space after number in baked eoc content

- bower.json
update coach to [coach-20170630.b](https://github.com/openstax/tutor-js/releases/tag/coach-20170630.b)
> no coach babelbjlejlbjelkbje

- bower.json
update coach to [coach-20170630.c](https://github.com/openstax/tutor-js/releases/tag/coach-20170630.c)
> coach next step fix

- src/scripts/modules/media/body/content-baked.less
This fixes [#283](https://github.com/Connexions/cnx-recipes/issues/283) in cnx-recipes
> Fix border-top appearing in answer key

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content-baked.less
fixes #1569 
also update learning objective styling to match notes
> equation numbering position, learning objective styling

- src/scripts/modules/media/body/content-baked.less
Addresses [284 in cnx-recipes](https://github.com/Connexions/cnx-recipes/issues/284).
> Style figure titles correctly

- src/scripts/modules/media/footer/attribution/attribution-template.html
Instead of all the changes in https://github.com/Connexions/webview/pull/1576, Alina requested we just change the email address in the footer for assignable webview.
> change email address in footer to supportATopenstax.org

- src/scripts/helpers/links.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/media.coffee
fix reload twice bug
fix page jump after hash change
fix index term cover up by header
Sorry it's slow because it is running in Dev mode and Phil's trackpad is very old
> fix reload twice bug

- src/scripts/modules/media/tabs/contents/contents-template.html
> apply max-two-lines to title link

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
> add requested punctuation for books message

- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.coffee
Waiting to load the text of the book count until the count has actually been loaded.
Also adding special case text for if there are 0 or 1 books found.
(example page in one book. not sure where to find one in 0 books to look at http://localhost:8000/contents/e6qfF73c@3/131-Chromosomal-Basis-of-Inher)
(https://github.com/Connexions/webview/issues/1620)
> Wait to load book count

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/modules/footer/footer-template.html
https://trello.com/c/NeeFE0g8/209-change-request-add-a11y-statement-to-cnxorg
TODO: translation in Polish
> Add accessibility statement to the footer

- src/scripts/modules/media/body/content-baked.less
> Answer Key entries on new line after number

- src/scripts/modules/header/header-template.html
* adds `id="nav-browse"` to the browse link
* adds `id="nav-about"` to the about link
* adds `id="nav-donate"` to the donate link
> Add ids to navbar links to facilitate better automation

- src/scripts/helpers/handlers/analytics.coffee
- src/scripts/loader.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/nav/nav.coffee
- src/scripts/router.coffee
... by not tracking the canonical URL.
This is not an ideal solution because it causes us to track the non-canonical URL. However, there isn't really a good central place that fires off analytics tracking so this seemed like the minimal fix to address Marketing's concern of double-counting pageviews.
Refs #1601
- `UA79034791` is the org-wide tracking code
- `UA302277982` is the book-specific tracking code
http://localhost:8000/contents/r-QzKsl_:JEgX-zGG
```
create UA-7903479-1 auto
UA79034791.send pageview /contents/r-QzKsl_:JEgX-zGG
create UA-30227798-2 auto
UA302277982.send pageview /contents/r-QzKsl_:JEgX-zGG
```
http://localhost:8000/contents/r-QzKsl_@7.23:JEgX-zGG@4/Introduction-to-Sociological-R
```
create UA-7903479-1 auto
UA79034791.send pageview …
```
> remove duplicate pageview counts

- src/scripts/models/content.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/media.coffee
This reverts commit 239667f7aeb7f5ae9915ed7a23f1847f58cff9c0.
> Revert ":bug: send canonical URL to book analytics"

- src/scripts/modules/media/nav/nav.coffee
This reverts commit d61eed67786e4a6876bbd5a3b328f62957342e28.
> Revert ":bug: handle clicking next/previous"

- src/scripts/modules/media/body/content-baked.less
> Fix inline display of answer key

- src/scripts/modules/media/body/content-baked.less
> Fix equation numbering style

- src/scripts/modules/media/media.less
> set z index of media.pinned to 10

- src/scripts/modules/media/body/content-baked.less
[Issue #1636](https://github.com/Connexions/webview/issues/1636)
> Fix wrapping around an image in exercises

- src/scripts/modules/media/body/content-baked.less
Fixed #1676
Didn't find any place that the commented out margin would affect badly, if you'll accept my changes I will remove the commented code.
> fixed distance between figures description and list below

- src/scripts/modules/media/body/content-baked.less
I've made a comment on it in the [issue 1640](https://github.com/Connexions/webview/issues/1640), pls take a look
> changed caption font size to 0.9em

- src/scripts/modules/media/body/content-baked.less
I had to override MathJax, I'm still not really sure if that's the correct way. I've checked few tables in other books, seems that it didn't affect them badly, but surely there's a need for QA in here.
#1655 issue link
> Issue 1655 spacing textalign in tables

- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.coffee
#1669 
Revert "Wait to load book count (#1621)"
This reverts commit dff42c00ca49ceb46272c4cac2410ce49e227fa2.
I believe that in previous version there was no translations for this lines so that code was working but now this is cousing an error so we reverted this. Thanks to @aiwenar 
cc @sisiz
> issue-1669-polish-text-on-english

- src/scripts/modules/media/body/content-baked.less
> Fixed design of College Physics Chapter outlines

- src/scripts/modules/media/body/content-baked.less
https://github.com/Connexions/webview/issues/1700
> Issue-1700

- src/scripts/modules/media/body/content-baked.less
Fix the equation display and tweak styles.
> Fix equations display

- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/body/content-common.less
https://github.com/Connexions/webview/issues/1704
> Issue-1704

- src/scripts/modules/media/body/content-baked.less
https://github.com/Connexions/webview/issues/1716
> Issue 1716

- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.coffee
#1728 
Add condition to show  div with `This page is not in any books` only when book is fully loaded
> Fix Issue 1728 - left pane shows loading message 'This page is not in any books' when page is in a book

- src/scripts/collections/featured-books.coffee
- src/scripts/collections/languages.coffee
- src/scripts/collections/licenses.coffee
- src/scripts/collections/site-status.coffee
- src/scripts/collections/subjects.coffee
Requires AND required for https://github.com/Connexions/cnx-archive/pull/565
> Made webview call the new extras single-field APIs

- src/scripts/modules/media/body/content-common.less
#1732 
Dots were showing only in baked books.
> issue 1732 remove dots, padding and margin from lists inside tables

- src/scripts/modules/media/body/content-baked.less
#1650
This PR propably should be merged after `https://github.com/Connexions/oer.exports/issues/3714` will be resolved?
@cc @openstaxalina
> issue 1650 imitate space with padding for .os-number inside eoc, eob

- src/scripts/modules/media/body/content-baked.less
> issue-1738 display images inside of notes as a block

- src/data/cms-books.json
- src/scripts/collections/featured-openstax-books.coffee
- src/scripts/modules/featured-books/featured-books-partial.html
- src/scripts/modules/featured-books/featured-books.coffee
- src/scripts/modules/featured-books/featured-books.less
merge master fixes into sprint branch
> merge master

- src/scripts/modules/media/body/content-baked.less
https://github.com/Connexions/webview/issues/1698
> Issue-1698

- src/scripts/models/contents/node.coffee
- test/scripts/models/contents/collection.js
- test/scripts/models/contents/page.js
Requires https://github.com/Connexions/cnx-archive/pull/566
Should speed up requests for page extras by not returning the list of books the page is in (most noticeable for College Physics).
> Request the contextual version of page extras

- src/scripts/modules/media/body/content-baked.less
#1767
Added code which I removed earlier because it was causing an error on devb but on katalyst it's already fixed.
> issue 1767 add padding for elements with data-type=media attribute

- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.less
Placed logo image in new img element with alt text
> Issue 1758

- src/scripts/modules/media/header/header-template.html
Gave button dialog role and added dialog title
> Issue 1759

- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/body/content-common.less
> move css to content-baked

- src/scripts/modules/media/body/content-baked.less
> ornery.orthrus.junior

- src/scripts/modules/media/body/content-baked.less
> Style end notes

- src/scripts/modules/media/header/header-template.html
- src/scripts/modules/media/header/header.less
#1823 
Added class to button to invert colors on focus
> Issue 1823

- src/scripts/modules/media/body/body.coffee
#1757 
Added aria-live assertive role to immediately read solution aloud when clicking show solution button
> Issue 1757

- src/scripts/modules/media/body/content-baked.less
> Remove extra padding in EOC numbering

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/modules/featured-books/featured-books-template.html
- src/scripts/modules/featured-books/featured-books.less
again with the google translate for the polish
> add copy to differentiate between community/openstax books on homepage

- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/nav/nav.less
> clickable search button in book view

- src/scripts/modules/media/body/content-baked.less
> Fixed alignment in wrappers

- src/locale/pl/dictionary.ftl
additional space was causing an error in polish version
> remove additional space

- src/scripts/loader.coffee
this was causing Safari & Edge browsers to fail
An untested attempt at a fix.
(Alternative to #1875)
> let the browser Download PDFs

- src/scripts/modules/media/body/content-baked.less
Small fix to repair some issues.
> Small display change exercises properly

- src/scripts/collections/featured-openstax-books.coffee
- src/scripts/models/featured-openstax-book.coffee
- src/scripts/modules/media/body/body-template.html
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/body.less
- src/scripts/modules/media/media.less
- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/contents.less
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/modules/media/tabs/contents/toc/section.coffee
> add toc to introduction page body

- src/scripts/modules/media/body/body.less
setting image height automatically in flexy containers is janky
> fix image height in about this book section

- .jenkins/deploy
Similar to Connexions/cnx-press#194
> Add a Jenkinsfile to release the Docker image

- src/scripts/modules/media/body/content-baked.less
#1913 
center text for data-align="center" attribute for `<td>`
> issue 1913 center text for data-align="center" attribute

- test/scripts/modules/header/header.js
- test/scripts/modules/media/footer/downloads/downloads.js
- test/scripts/modules/media/header/popovers/book/book.js
> Issue 1891

- src/scripts/modules/media/body/content-baked.less
#1904 
style learning objectives section to match pdf version
> issue 1904 style learning objectives section

- src/scripts/modules/media/body/content-baked.less
> Fixed display style of figures in exercises

- src/scripts/modules/media/footer/footer.coffee
#1829 
disable license view
I've commented those lines instead of deleting them because I'm not sure if this will be needed in future
> issue 1829 - disable license view

- src/scripts/modules/media/body/content-baked.less
https://github.com/Connexions/webview/issues/1902
Added a proper css rule for [data-valign="top"].
> 1902 margin in tables with bullet lists

- src/scripts/modules/media/body/content-common.less
https://github.com/Connexions/webview/issues/1911
> Issue-1911

- src/scripts/modules/find-content/find-content-template.html
- src/scripts/modules/find-content/find-content.coffee
- src/scripts/modules/find-content/find-content.less
- test/scripts/modules/find-content/find-content.js
https://github.com/Connexions/webview/issues/1890
> allow clicking on search icon on /browse

- src/index.html
Required by the grunt library that does the cache-busting
> Added extension to /scripts/main for cache-busting to work

- Gruntfile.coffee
- src/scripts/models/content.coffee
- src/scripts/modules/media/body/body.less
https://github.com/Connexions/webview/issues/1951
I'm not sure if that's the proper `max-width` to be used. Should I specify this to be `screen` and `portrait` also or it's ok the way it is?
Could you please verify that?
> 1951 mobile book description

- script/build-settings-from-env
A step towards dynamic configuration... This script will be run as part of the container startup script. The idea is to be able to configure the container dynamically at runtime.
Not perfect, but does the job. 🍄
> Add script to write settings.js from env vars

- .jenkins/deploy
- .jenkins/gen_env_list.py
This will update the staging stack deployment of webview then proceed to run the integration tests over the newly deployed service.
> Add jenkins pipeline stages to deploy and integration test

- src/scripts/modules/window-with-sidebar/window-with-sidebar.less
#1626 
resize toc to be full width below 640px resolutio
> issue 1626 resize toc to be full width below 640px resolution

- src/scripts/modules/media/title/title-template.html
> remove google plus link

- src/scripts/configs/embeddables.coffee
- test/scripts/modules/media/body/body.js
#1794 
Let me know if this is enough for this issue.
Here is documentation for `encodeURIComponent()`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
> issue 1794 encodeURIComponent for exercises tags

- src/scripts/modules/media/footer/metadata/metadata.less
> Issue 2000v2 

- src/scripts/modules/media/media.coffee
Canonical URL of page being viewed in a book or a page viewed outside of a book, but has a canonical uuid
Canonical URL of a page that is not in a book
> Change to read canonical uuid from page json

- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/body/content-common.less
https://github.com/Connexions/webview/issues/2027
> issue-2027

- src/scripts/modules/media/body/content-baked.less
https://github.com/Connexions/webview/issues/2025
> issue-2025

- src/scripts/modules/media/body/content-common.less
https://github.com/Connexions/webview/issues/2042
> issue-2042

- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/tabs/contents/contents.less
#2021 
Toggling button is used in few places which mean there have to be `if statement` because there isn't always a `.toc`.
I've also added some padding because there wasn't any blank space between borders and text.
> issue 2021 fix toggling sidebar at page view

- README.md
Added Ubuntu 16.04 install instructions
> Added Ubuntu 16.04 install instructions

- src/scripts/modules/search/results/filter/filter.less
#2028 
Fast fix, it seems like I forgot to add one attribute to commit
> issue 2028 add flex-wrap for filters columns

- src/scripts/modules/media/header/header.coffee
#2092 
This issue is not occuring in localhost but I'm pretty sure thats caused because of change I've made in #2070. This pr is reverting that change.
It also mean that issue #2048 is still not fixed.
> issue 2092 reapply change:currentPage.loaded listener in header

- src/locale/en-US/dictionary.ftl
- src/scripts/modules/splash/splash-template.html
https://github.com/Connexions/webview/issues/2084
> issue-2084

- src/locale/en-US/dictionary.ftl
- src/scripts/pages/browse-content/browse-content-template.html
https://github.com/Connexions/webview/issues/2085
> issue-2085

- src/scripts/modules/search/advanced/advanced-template.html
- src/scripts/modules/search/advanced/advanced.coffee
add error msg to advanced form
issue - https://github.com/Connexions/webview/issues/2086
> issue-2086

- src/scripts/modules/media/body/content-baked.less
Bold reference number. It's realated to issue #2155. Also that issue is solved by PR https://github.com/openstax/cnx-recipes/pull/769.
> Bold reference number

- src/scripts/modules/media/body/content-baked.less
> added display block to img in end of section problems and solutions

- src/scripts/modules/media/body/content-baked.less
> added margin-top to os-solution-container paragraphs in examples

- src/scripts/modules/search/advanced/advanced-template.html
- src/scripts/modules/search/advanced/advanced.coffee
addresses issues: 
https://github.com/openstax/webview/issues/2086
https://github.com/openstax/webview/issues/2091
> issue-2086-2091

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2136
will affect books that are described in https://docs.google.com/spreadsheets/d/1xRt2in0XaFpA5no6yLQbXBf7Q7pKeJ4yzI4yRpFacKY
> changed list style type in review questions to upper alpha

- src/scripts/models/content.coffee
- src/scripts/models/contents/collection.coffee
Slight modification to first try.
> Second try at displaying empty collections correctly

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2160
> issue-2160

- src/scripts/modules/media/body/content-baked.less
scaled-down: 60% content width
scaled-down-30: 30% content width
Link: Issue #2171
> Implement scaled-down-30 class

- src/scripts/modules/media/body/content-baked.less
RE
https://github.com/openstax/webview/issues/2160
> add margin to links in exercises

- src/scripts/modules/media/body/content-baked.less
Types of lists in Review Questions were changed to upper-alpha.
> changed type of list to upper-alpha-issue2176

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2186
> issue-2186

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2198
> removed dots from unordered lists in the preface

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2197
> changed display of paragraphs inside solutions in composite page

- src/scripts/modules/header/header-template.html
- src/scripts/modules/media/header/header.coffee
https://github.com/openstax/webview/issues/2196
> issue-2196

- src/scripts/modules/media/body/content-baked.less
Issue: https://github.com/openstax/webview/issues/2215.
> Removed bold from links inside sections

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2234
> fixed answer key display

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2232
> set span images display to block

- src/scripts/modules/media/body/content-baked.less
This should solve https://github.com/openstax/webview/issues/2237 and https://github.com/openstax/webview/issues/2242
> changed figcaption display to block so unnumbered captions display correct

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/1914
This will affect all baked books (all paragraphs inside `os-problem-container` within appendix exercises).
> removed padding from paragraph

- src/scripts/collections/featured-openstax-books.coffee
Added "apps/cms/" to API call.
> Modified cms API url

- src/scripts/modules/media/body/content-common.less
https://github.com/openstax/webview/issues/2262
> issue-2262

- src/scripts/modules/media/body/embeddables/exercise-template.html
update exercise template to match cnx-epub
https://github.com/openstax/webview/issues/2274
https://github.com/openstax/cnx-epub/pull/153
> issue-2274

- src/scripts/modules/media/body/content-baked.less
Issue: https://github.com/openstax/webview/issues/2287
> Display exercises inside module

- src/scripts/modules/media/body/content-baked.less
Issue: https://github.com/openstax/webview/issues/2289
> Remove title from composite chapter

- Jenkinsfile
Remove Deploy to Staging Stack from Jenkins pipeline
> Remove Deploy to Staging Stack from Jenkins pipeline

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/modules/media/body/body.coffee
- yarn.lock
for: https://github.com/openstax/webview/issues/2301
> Add support for previous version of footnotes
