openstax/webview

- src/scripts/modules/media/header/header.coffee
`currentPageData.encodedTitle = encodeURI(currentPage.title)` was always setting the `encodedTitle` to undefined, because `currentPage` was set to `@model`, while `currentPageData` was the `toJSON` version of the content.  `@model` never had a `title` property attached to it (it would be in `@model.attributes.title` or accessible with `@model.get('title')`).
> Fix issue where page title was undefined

- src/scripts/modules/media/body/body.coffee
https://github.com/Connexions/webview/issues/925
changePage() method is triggered on click event for link in body.coffee. The copy link in blockish elements does not have href.
> Check for undefined href

- src/scripts/modules/media/editbar/modals/list/section.coffee
Instead of proxying change event for title, the code is listening for change:changed so the view is rendered when a title or content is changed within a section.
Fixes https://github.com/Connexions/webview/issues/950
Fixes https://github.com/Connexions/webview/issues/947
> Fix for scrolling in modules

- src/scripts/modules/workspace/results/list/workspace-item-partial.html
Small change that fixes status link. It was pointing to role acceptance for every state except Draft.  It is now pointing to the content for every state except "Awaiting acceptance'.
> Role acceptance link only displayed when needed

- src/scripts/helpers/backbone/views/editable.coffee
- src/styles/main.less
@edwoodward found a problem with this content http://localhost:8000/contents/6adb2f84-9885-4207-bf83-563a511d6acd@3/What_Is_Sociology?? He could not add content to the end of the page because there is no p tag after the content. This PR adds the p tag to the end of the content if it doesn't exist.
@pumazi created this issue https://github.com/Connexions/webview/issues/775 because empty p tags were being added to the summary. This PR is only adding the empty p tag to the draft itself, not the summary.
> Place cursor at the end of content

- src/scripts/modules/media/footer/attribution/attribution.coffee
We do not need to include a templateHelper in attribution.coffee for id. When toggling between book and page, the view is rendered and getVersionedId method is called, adding the version to the end of the id in the attribution links.
Fixes Ed's last comment in https://github.com/Connexions/webview/issues/1026
> Remove template helpers from attribution.coffee

- src/scripts/modules/media/body/body.coffee
Processing instructions modal was rendering multiple times and on published pages.
> Fix for PI modal rendering multiple times

- src/scripts/modules/media/body/embeddables/exercise-template.html
shows only first item from exercises, see openstax/tutor-server#246
if first item does not exist, show blank
tested manually with [a book](http://localhost:8000/contents/7db9aa72-f815-4c3b-9cb6-d50cf5318b58@4.128:2/Updated_Tutor_HS_Physics_Conte) on archive.cnx.org
> show only first item from exercises api, otherwise, show blank

- bower.json
- package.json
- src/scripts/config.js
This update switches back to using underscore rather than lodash. The latest version of lodash is not compatible with the latest version of Backbone. Underscore has made improvements.
Will need to run `bower uninstall lodash` to remove the dependency files from bower components.
> Update dependencies on master

- src/scripts/modules/media/body/body.coffee
This fixes issue where links to figure elements in content was being displayed as '[link]'. Also takes into account exercises, problems and notes where the tagName is 'div' and we need the data-attribute to display the proper link text.
> Fix figure links

- src/scripts/modules/browse-content/browse-content-template.html
Simple change to the Contents Page (when browsing content) that simply disables tabbing to superfluous links.  Some overlapping issues were fixed in the previous PR for Home Page accessibility.
> Disable tabbing to superfluous image links

- src/index.html
- src/scripts/loader.coffee
- src/scripts/modules/featured-books/featured-books-partial.html
- src/scripts/modules/featured-books/featured-books-template.html
- src/scripts/modules/find-content/find-content.less
- src/scripts/modules/header/header-template.html
- src/scripts/modules/header/header.coffee
- src/scripts/modules/header/header.less
Issues remaining:
- Zendesk has some accessibility issues that can't be fixed
- Carousels in general are very unfriendly, especially to users with greater accessibility needs
> Improve Accessibility of Home Page

- src/styles/main.less
Bootstrap has the following 2 rules for `.caret`:
```
border-top: 4px dashed;
border-top: 4px solid \9;
```
Unfortunately, we're interpreting the 2nd rule as overriding the first when minimizing CSS (it's intended only as a fix for IE9).  Since we don't support IE9, this PR overrides those rules to ensure a valid `border-top` rule is used.
> Override Bootstrap caret rule so it shows in dist

- src/scripts/modules/media/editbar/license/modals/license.coffee
- Use `_.find` instead of `_.each` to match licenses faster
- Improve robustness to prevent an unmatched license from crashing the app
- Throw a warning when no license is matched to help with debugging
> Improve robustness of License module

- src/scripts/modules/media/body/body.coffee
After reviewing an issue that @edwoodward found yesterday, it appears that the sims modal was appending to the dom no matter if the sims link was present or not. 
https://github.com/Connexions/webview/issues/1159
> Add modal to dom only if os-interactive-link is present

- src/styles/main.less
The `.social-button` mixin defines defaults for `background-size` and `background-position`, which should be getting overridden by the new styles defined after them (and is appropriately overridden in dev).  However, in the dist version, the CSS compressor makes an unfortunate choice that causes the rules to appear in the wrong order.  Adding `!important` ensures they will still take precedence.
> Prevent overriding styles in dist build

- src/scripts/models/search-results.coffee
- src/scripts/modules/search/advanced/advanced.coffee
- src/scripts/modules/search/header/header-template.html
- src/scripts/modules/search/header/header.coffee
- src/scripts/modules/search/results/list/list-template.html
- src/scripts/pages/error/error.coffee
Set search to timeout at 1 minute. Inform user they can try reloading,
or refining. Advanced Search button carries new “criteria” parameter
along, which pre-fills the form the way they had it.
> Advanced search limit results

- src/scripts/modules/search/results/list/list-template.html
Ed wanted the search timeout to explicitly refer to Advanced Search. This got a “looks good”.
> Wording tweak

- src/scripts/modules/search/advanced/advanced.coffee
The Advanced Search field-filling routine was failing for searches that
did not have queryField:term format (such as come from the Search box)
> Search criteria fix

- src/scripts/modules/media/footer/footer-template.html
- src/scripts/modules/media/footer/footer.coffee
- src/scripts/modules/media/tabs/tabs.coffee
Header tabs and footer tabs have role attributes. Tab content panes
have “tabpanel” role and have aria-hidden=“true” when hidden, and are
tied back to tab ids via aria-labelledby attribute.
> Aria attributes for tabs

- src/scripts/models/contents/node.coffee
- src/scripts/modules/media/header/popovers/book/book-template.html
Turns out we don’t want to restrict EPUBs specifically.
> Only exclude downloads whose state is not good

- src/scripts/modules/media/body/content.less
Don't constrain img width further than necessary (it's already constrained by the figure it's in).
Fixes:
http://cnx.org/contents/8fee8a58-183e-4ac9-8b56-4dc08b25cca4@1.1:16/Sources-for-Fords-Cavalry-tril
http://legacy.cnx.org/content/m41024/1.1/
> Remove superfluous img width restraint

- src/scripts/modules/featured-books/featured-books-partial.html
- src/scripts/modules/featured-books/featured-books.less
- src/scripts/modules/media/footer/attribution/attribution-template.html
- src/scripts/modules/media/footer/downloads/downloads-template.html
- src/scripts/modules/media/footer/footer.less
- src/scripts/modules/media/footer/history/history-template.html
- src/scripts/modules/media/header/popovers/book/book-template.html
- src/scripts/modules/media/header/popovers/book/book.less
- src/scripts/modules/media/title/title-template.html
- src/scripts/modules/media/title/title.less
- src/scripts/modules/search/results/filter/filter-template.html
- src/scripts/modules/search/results/filter/filter.less
- src/scripts/pages/about/default/default-template.html
- src/scripts/pages/about/people/people-template.html
- src/scripts/pages/donate/default/default-template.html
Closed gaps in h-levels: h2 comes after h1; h3 comes after h2, etc., not
h5 after h3 after h1. Adjusted classes and .less files so most render
the same as before, rather than changing size. Exception: On “About
Us”, allowed “How it works” and “Frictionless Remix” to be smaller than
top-of-page header.
> Heading hierarchy

- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/section.coffee
- src/scripts/modules/media/tabs/contents/toc/section.less
To resolve the numbering mismatch between PDF and online, for books with printStyle beginning with “ccap-“:
Pages that are the first page in a section and whose title begins with “Introduction” are not numbered.
> Toc numbering

- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/modules/media/tabs/contents/toc/section.coffee
- src/scripts/modules/media/tabs/contents/toc/section.less
CSS numbering cannot work for sequential chapters, because unexpanded
sections are not on the page and so cannot be counted. This patch
applies a “chapter” attribute to TOC model entries and includes it in
the HTML, with CSS styling similar to the old CSS-numbered chapters.
Books with a printStyle attribute like ccap-* have continuously
numbered chapters, all bottom-level entities are numbered #.#, and
higher level entities are just #.
Non-ccap books are numbered old-style, with all levels of numbers (e.g.
5 > 5.1 > 5.1.1)
> Toc unit numbering

- src/scripts/helpers/backbone/views/base.coffee
- src/scripts/modules/media/media.coffee
The description meta tag is currently just the book summary.  With this change, when individual pages have their own abstract/summary, the description tag is set to this instead.  Otherwise, it remains the same as before.
> Enhance description meta tag

- src/scripts/helpers/links.coffee
- src/scripts/modules/media/body/body.coffee
- test/scripts/helpers/links.js
linksHelper.getPath now returns short-id@version for both book and
page, which covers all navigation links.
Content body checks that the URL matches the canonical path or updates
it if not.
> Ensures URL for content is canonical

- bower.json
- src/scripts/config.js
- src/scripts/modules/media/body/body-template.html
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/body.less
- src/scripts/settings.js
- src/styles/main.less
Ready for review.  Will show concept coach button for book [`8QUzyvgD`](http://localhost:8000/contents/8QUzyvgD) -- linked to local at 8000.  The button should not show on other books.
Clicking on the link locally should trigger a request to tutor-dev but CORs will be denied.  The full widget will not work until on [dev.cnx.org](https://dev.cnx.org), and tutor-dev is also up and running.
Once it's working, CC should look like this: http://openstax.github.io/concept-coach/.
> Cc load initial

- src/scripts/modules/media/footer/metadata/metadata.less
The CSS expected the container to have relative position.
> Fix: Book/Page toggle for Metadata not displaying

- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/nav/nav.less
- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.coffee
Added link that says "Back to Table of Contents" to search results; clicking it calls clearSearchResults function, leaving search term intact
Changed clear search icon to circle-times to match mockup
Used clear-search class so it’s not tied to particular icon
> Back to toc

- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/title/title.less
Only show header when scrolled to (almost) top. Hide header when scrolled down a portion of the window height. When hiding header, reduce title size.
> Change header hiding

- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/page.coffee
(Backward-compatible)
Handle change from “headline” to “snippet” in the data object
Display match count (if provided)
> Handle new snippet format

- src/scripts/pages/browse-content/browse-content.coffee
The way the Find Content bar was being inserted was causing it to
appear twice. Moving it allows me to use the standard region .show.
> Move findContentView to page code

- src/scripts/modules/header/header.coffee
This is a quick hack to lazy-load Zendesk with the header so that
its script executes and adds the content after our app has
overwritten the body tag that it appends to.
> Restore Zendesk

- src/scripts/loader.coffee
bootstrap styles were being appended after `header.less` and therefore taking precedence over styles from `header.less`
> adjust styles ordering to fix header spacing bug 

- bower.json
- src/scripts/modules/media/body/body-template.html
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content.less
- src/scripts/modules/media/body/embeddables/cc-launcher-template.html
> moves cc launcher to inside content, after review, but before glossary

- src/scripts/loader.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/tabs/contents/toc/section.coffee
If header was in hidden/compact mode before page change, the window will scroll there after.
Also, Introduction pages will display chapter numbers by their titles (but TOC still will not)
Fixes 1284
> Keep header pinned after navigating

- src/scripts/modules/media/body/body.coffee
For Edge bug where Concept Coach doesnt seem to be showing after cc load
> put a window.scrollTo after cc load

- bower.json
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/media.coffee
esp when using back button for example
also,
* no more rando scrolling on page change after cc opening
* media doesn't overwrite the base `close` function while still `off` on `closing`
> cc nicely cleans up and prevents multiple CC events hanging out

- src/scripts/modules/media/body/body.coffee
trying to call cc's handle resize on pages without a mounted cc was causing errors.
> only handle cc resize when cc is opened

- src/scripts/router.coffee
Redirects are giving us properly encoded URIs, and we were looking for
@ and : in the pathname.
> Fix non uuid address redirects

- src/scripts/modules/header/header.less
- src/scripts/pages/app/app.coffee
Lost the login link with the donate button. Restored.
Tightened up the spacing a bit
> Restore legacy login link to main pages

- bower.json
- src/scripts/helpers/links.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/embeddables/cc-launcher-template.html
includes:
* opening coach changes urls
* such that when you click back while coach is opened, it closes the coach and leaves you back on the same page you launched the coach from
* cnx nav links ignore the coach view query parameter by default, so that the cnx page nav for back and next navigates to the destination page with the coach closed
* taking the coach mounting out of a deferred
* clean up the `isCoach` -- no need for it to be a template helper anymore
Will be followed up by an update to the coach version after openstax/concept-coach#104 is merged, although this PR can be merged independent of a coach update
> Coach with urls

- src/scripts/models/content.coffee
- src/scripts/settings.js
If book contains no pages, don’t 404 in setPage, just return.
Fixes #1335
> Handle no-pages condition

- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/pages/app/app.coffee
Pinned navbar obscures top of window, so when going to id, scroll back
by the height of the bar.
Removed some old scrolling code for element that no longer scrolls
Fixes #1344
> Handle scroll-to-anchor in content

- src/scripts/modules/media/tabs/contents/contents.coffee
allPages cache was not being reset when contents changed
Also reduced excessive calls by debouncing, and removed extraneous call to render
> Fix editor toc

- src/scripts/models/content.coffee
- src/scripts/models/contents/collection.coffee
- src/scripts/models/contents/node.coffee
- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/tabs/contents/contents.coffee
- src/scripts/modules/media/tabs/contents/popovers/add/modals/add-page.coffee
Fix remaining issues with TOC editing:
- getPage was being called on Page objects and not simply returning the object
- already-published pages would not insert into TOC
- after adding, last added page should become current page
- chapters were not being renumbered when TOC was re-arranged
> Fix toc editor

- src/scripts/config.js
- src/scripts/helpers/handlers/analytics.coffee
Used [ga-debugger](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging) to trace problem
Only affects dev version, wasn't causing problems currently, but this error broke less rendering in sims repo for example in the latest Chrome
`require-less` tries to use XHR `async=false` option by default, this [no longer follows spec](https://xhr.spec.whatwg.org/#sync-warning)
> tracker name for GA must be alphanumeric

- src/scripts/helpers/handlers/analytics.coffee
strips of non-alphanumeric characters from account string
Previous solution from #1375 meant all trackers would get confused since the same name would be submitted for various accounts.
> allow unique trackers based on ga account id input to analytics.send

- bower.json
Earlier release had old code as result of a a missed `npm install` step.
Contains
* Remember free response when switching between exercises
* Screen to update student identifier
> Update CC with fixed build

- bower.json
coach is being rolled back without student id update and free-response recall with openstax/react-components#42, and openstax/concept-coach#128 from ask-us fix #1381 
The release notes for this [current version of concept-coach](https://github.com/openstax/concept-coach/releases/tag/d-20160210.b) are as follows:
This release is [d-20160128.a](https://github.com/openstax/concept-coach/releases/tag/d-20160128.a) -- the last official release -- with:
* :footprints:ture, :bug:fix allow passing through click event for filtering, for ask us button
* openstax/concept-coach#128 
* :bug:fix add recovery to coreGroups
* openstax/react-components#42, related to openstax/tutor-js#973
Original targeted release was [d-20160209.a.candidate](https://github.com/openstax/concept-coach/releases/tag/d-2016020 …
> coach is being rolled back

- src/scripts/modules/media/media.coffee
On page load, scrolling to hash runs before everything has loaded.
Experimentally, I found that about 1/8 second delay works.
Fixes #1367
> Fix: load page at hash scrolls too far

- Gruntfile.coffee
The files load but I am not sure about the best places to set breakpoints to verify. Also, I did not look very hard to see if `requirejs` could include the original `.coffee` source (see screenshot)
Fixes #1378
> adds source maps

- bower.json
Update with latest coach [release](https://github.com/openstax/concept-coach/releases/tag/d-20160226.a) that fixes the free response caching so that free response is remembered even when a different question has been answered.  see [these](https://www.pivotaltracker.com/story/show/113852189) [ticket](https://www.pivotaltracker.com/story/show/113851607) for details
> update coach with free response fix

- src/scripts/modules/media/media.coffee
from when hash changed query is not found.  This would happen whenever hash events fire and it's `#` or even when it's a valid hash change but the element is not found.
> prevent Cannot read property 'top' of undefined errors

- src/scripts/modules/media/tabs/contents/toc/page-template.html
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/modules/media/title/title-template.html
> Allow HTML to display correctly in titles

- src/scripts/models/contents/node.coffee
currentPage.abstract retained a cnxml wrapper which caused the header Summary toggle to display even when no abstract was present.
> Summary toggle shows only when abstract summary exists.

- src/scripts/models/contents/node.coffee
- src/scripts/modules/media/tabs/contents/contents.coffee
Adds a check so that table of contents is not numbered when the book has been cooked. Also adds a method to node.coffee to check for the "collated" attribute.
> fix: turns off numbering when the book is collated

- src/scripts/modules/media/body/body.coffee
- src/scripts/settings.js
fixes [:bug: Launch Concept Coach is missing](https://www.pivotaltracker.com/story/show/123141311), looked the same since exercises get hidden, it doesnt matter if coach goes before or after.  this way, since dom get traversed from parents down to children, inserting before the first will ensure that coach never gets nested inside an exercise that was just hidden
> fixes coach embed so it doesnt nest inside a hidden exercise section

- src/scripts/modules/media/body/body.coffee
The code was for rewriting href like
"/contents/c8bdbabc-62b1-4a5f-b291-982ab25756d7" to
"/contents/031da8d3-b525-429c-80cf-6c8ed997733a@9.30:1" when the page id
is within the current book.
The code was not matching href like
"/contents/c8bdbabc-62b1-4a5f-b291-982ab25756d7#table" because it was
using everything after the "/contents/" as the page id when matching
against pages in the book.
> Look for page in book using page id in href when rewriting href

- bower.json
Fixes bug where after answering the free response in Concept Coach, something must be clicked to show the free response answer on the multiple choice step. Clicking on an answer selects the answer, but doesn't activate the submit button. Clicking on the breadcrumb, an answer, or window refresh will show the free response answer and clicking on a multiple choice answer at this point works.
> Update CC; fixes bug with tasks using old state

- src/scripts/models/contents/node.coffee
When a user derives a book, the page is not draft, so it tries to use
the archive contextual url which is 404 not found.
> Use the authoring url if page is draft and archive url if book is draft

- src/scripts/modules/search/advanced/advanced-template.html
On cnx.org, when we use advanced search to search for content in a
particular language, instead of doing /search?q=language:da, we're taken
to /search?q=language:6 and get no results.
When search languages are filtered, "languages" is an array and "@key" is
the array index.  This commit changes the code to use "id" instead,
which is the iso code.  (See src/scripts/collections/languages.coffee)
> Use iso code instead of array index for languages in advanced search

- src/scripts/modules/media/body/body.less
I don't think this is necessarily the right way to solve this problem/maybe I don't understand the full scope behind the list styles defined [here](https://github.com/Connexions/webview/blob/master/src/scripts/modules/media/body/content.less#L182-L365).
For example, if the purpose is to have custom control over the enumeration of `ol`s then why is this [`list-style-type`](https://github.com/Connexions/webview/blob/master/src/scripts/modules/media/body/content.less#L309) not set to `none` since the [`::before`](https://github.com/Connexions/webview/blob/master/src/scripts/modules/media/body/content.less#L316-L321) will be enumerating?
Or, instead, should these [selectors](https://github.com/Connexions/webview/blob/master/src/scripts/modules/media/body/content.less#L351-L352) be a little …
> override list styles for coach so that they have single numbers

- bower.json
- src/scripts/config.js
Update concept coach with [latest release](https://github.com/openstax/tutor-js/releases/tag/coach-20160812.b), changes for using coach from mono-repo
> update coach to latest release and make it mono repo compatible

- src/scripts/modules/media/body/content.less
Make the CSS for suppressing footnote numbers work. (style: none)
> don't number footnote list w/ CSS

- src/scripts/modules/media/body/body.coffee
As the update #1452 causing this is not yet on production -- you'll see coach [here on production](http://cnx.org/contents/JydfSfIS@3.7:ivpbwI-1@8/Newtons-Second-Law-of-Motion-C), but [not on qa](http://qa.cnx.org/contents/JydfSfIS@2.2:ivpbwI-1@8/Newtons-Second-Law-of-Motion-C)
> fix missing coach on some sections, i.e. 4.3 in college physics

- src/scripts/modules/header/header.coffee
- src/scripts/router.coffee
`session.update` is not needed on non-editor enabled webview.
Do not put into `master`, for merging into `production`
> remove all calls of session.update

- bower.json
- src/scripts/modules/media/body/body.less
Updates coach to [latest release](https://github.com/openstax/tutor-js/releases/tag/coach-20161006.a) with Safari warning, also fixes closing on no exercises error
> updates coach to latest with safari warning, style updates for coach only

- src/scripts/modules/media/body/content.less
Should work for `<ul>/<ol>`, `<ul data-display=“inline”>`, and inline
lists (`<span data-type=“list”>`). refs #1461, #1460
(see the giant comment in the diff which contains the test code that is rendered here)
`<ul data-bullet-style="...">` myBullet, none, bullet, open-circle, pilcrow, rpilcrow, section, asterisk, dash
`<ol data-number-style="...">`arabic, upper-alpha, lower-alpha, upper-roman, lower-roman
`<ul/ol data-display="inline" data-bullet/number-style="...">` (see above examples for the order of values)
`<span data-type="list" data-list-type="bulleted/enumerated">...`
`<ul/span data-labeled-item="true">`
- add some padding/margin for inline numbered/bulleted lists
- implement `<span data-type="list" data-display="block">` (maybe not necessary?)
> fix lists so they are numbered better

- bower.json
- src/scripts/config.js
pulls in latest [coach updates](https://github.com/openstax/tutor-js/releases/tag/coach-20161221.a) and coffeescript fix in #1476
> Update coach against production

- src/scripts/config.js
if you ever clean out your `bower_components` folder<sup>[*](#myfoot)</sup> and re-install, a newer not-exactly-compatible version of `coffeescript` gets installed from the `require-cs` [dependencies](https://github.com/requirejs/require-cs/blob/842e8b8568536bcf7efcbea756560c6d7373e5ff/bower.json#L7).  they've [moved their browser-side compiler](https://github.com/jashkenas/coffeescript/compare/1.11.1...1.12.0#diff-45f508b714a4ac328c10a4c5a0e09dcaL304) between versions `1.11.1` and `1.12.0` from the `extras` subdir to `docs/v#{majorVersion}/browser-compiler/`.
I suspect this might happen even without purging `bower_components`...anyways, `coffeescript@1.12.0` was released 16 days ago so that might be why we haven't run into this issue yet
<a name="myfoot">*</a>which, really we should …
> coffeescript compatibility

- src/scripts/modules/media/header/header-template.html
- src/scripts/modules/media/header/header.coffee
- src/scripts/modules/media/header/header.less
This also removes the need for a toggle JS and an anchor
expanded:
<details>
<summary>
nothing selected</summary>
</details>
<details>
<summary>
collapsed again</summary>
</details>
<details>
<summary>
Old Code expanded</summary>
</details>
> use an accessible version of the summary toggle

- bower.json
Updates various labels to say "link" vs "code" for enrollment
Fixes bugs with
* Second semester banner link
* continue button not enabled
* Summary missing from breadcrumb
* Duplicated notification
> Update CC; bugfixes and wording updates

- bower.json
Updates the course has ended bar's second-semester action
> Bump CC to version with updated re-enroll message

- src/scripts/modules/media/header/header.less
Previously the button was hidden on smallest screen size, this displays it with some margins
> Display display Jump to CC button, regardless of screen size

- Gruntfile.coffee
- src/index.html
- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
This pull request resolves bugs:
1. Website staging.cnx.org is not loading in IE 11.
2. Missing space at the bottom of the content where the license is displayed. You have to go to the 2nd page of a book to see it.
We also sent a PR to the our version of l20n on the https://github.com/katalysteducation/l20n.js so you have to do `bower update` to get new version of l20n which contains fixes to use hyperlinks in the FTL code. This pull request resolves bugs:
1. License display should be a link to Creative Commons. The href is missing in the <a> tag
> Fix for the IE 11

- .travis.yml
- package.json
- script/check-templates-for-non-i18n-text.js
From katalysteducation/webview#1 (see for some discussion).
This parses all of the HTML files (handlebars templates) and checks to see if any text nodes exist after doing the following:
1. removing the text nodes inside elements with `[data-l10n-id]`
1. remove `<script>` tags
I will try to circle back later (but no guarantees) to add better messages and maybe check that the `[data-l10n-id]` values exist
add `<div>foo</div>` to the bottom of a `src/scripts/pages/*/*-template.html` file and run `npm run-script posttest`
> check that all strings are localized

- bower.json
- src/scripts/config.js
[CustomEvent](https://github.com/katalysteducation/l20n.js/blob/master/src/bindings/dom_localization.js#L186) was throwing off [IE 11's game](http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work).
> CustomEvent polyfill is needed for IE 11 as well

- script/check-templates-for-non-i18n-text.js
- src/locale/pl/dictionary.ftl
This is a followup to issues raised in #1521
It checks that the l10n keys which are found in the HTML templates actually exist in the `dictionary.ftl` files.
And unsurprisingly, it finds some missing ones 😄  (see Travis output):
```
BUG: Missing key in ./src/locale/pl/dictionary.ftl: 'textbook-editor-toggle-navigation'
```
<details>
<summary>Click me for the full list</summary>
I just commented out the `process.exit(1)` line in the `.js` file
```
BUG: Missing key in ./src/locale/pl/dictionary.ftl: 'textbook-editor-toggle-navigation'
BUG: Missing key in ./src/locale/pl/dictionary.ftl: 'textbook-editor-edit'
BUG: Missing key in ./src/locale/pl/dictionary.ftl: 'textbook-editor-normal-text-button'
BUG: Missing key in ./src/locale/pl/dictionary.ftl: 'textbook-editor-normal-text'
BUG: Missing …
```
> verify that the l10n keys exist in the dictionary

- src/scripts/config.js
From https://www.mathjax.org/cdn-shutting-down/ . This updates MathJax to 2.7.0 (from `2.6-latest`) and changes the domain to be cloudflare .
An alternative would be to build mathjax locally and host it as part of webview but that would increase the JS file size significantly. 
Chunking could bring the size back down a bit but would require a bit more dev work to only load MathJax when needed. And make sure the font files are hosted properly (correct path and content type headers)
> update mathjax and move the CDN domain

- Gruntfile.coffee
It seems `requirejs` occasionally times out when building the `main.min.js`. One case where this happens is when Jenkins is running more than one job at a time.
This should _hopefully_ fix the problem.
> Increase the timeout for requirejs modules

- src/scripts/config.js
https://github.com/katalysteducation/l20n.js/pull/1 merged, this is no longer needed, and may be causing problems sometimes on qa.
> dont need the init since the documentReady pr has been merged

- src/scripts/modules/footer/footer-template.html
The footer of CNX lists 20 Million Minds Foundation, but that organization is now called the Michelson 20MM Foundation. Therefore I corrected it by replacing the old name with the new one.
> Fix the bug about orgnization's name in the footer

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/helpers/backbone/views/base.coffee
- src/scripts/helpers/handlebars/stripTags.coffee
- src/scripts/helpers/strip-tags.coffee
- src/scripts/modules/media/header/header-template.html
As a stopgap solution while waiting for https://github.com/projectfluent/fluent.js/issues/37 to be resolved this strips the HTML tags out of the `<title>` and the Page Title.
/cc @reedstrm
> strip HTML tags from the page title

- src/scripts/modules/media/body/body.coffee
When navigating to a button, descriptive text didn't present to screen reader users to indicate the function of the button.
Therefore I fixed this bug by setting the aria-label according to the status of the attribute aria-expanded.
> Fix the Empty Button bug

- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/nav/nav.less
- src/scripts/modules/media/tabs/contents/contents-template.html
Fixed regression so that when there are no results it is reported to the user
Added a loading icon to the in book search
Loading icon looks like this:
But could easily be changed to this one: (not sure which goes better with the ux, and the openstax brand look. Fred and Nathan said there wasn't an openstax standard)
> In book search

- script/bootstrap
- script/build
- script/setup
- src/scripts/settings.js
This changes `./script/setup` to just install the dependencies. Previously the script would also build the `./dist/` directory but that has been moved to `./script/build`.
> Clean up the setup script

- src/scripts/loader.coffee
@reedstrm noted that `l20n` sometimes does not load. This attempts to ensure `l20n` runs after the document loads.
> ensure l20n loads after DOM is loaded

- src/scripts/modules/media/body/_make-block.less
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/body/content-common.less
- src/scripts/modules/media/body/content-raw.less
- src/scripts/modules/media/body/content.less
fix [#206](https://github.com/Connexions/cnx-recipes/issues/206)
Also, make note styling consistent across all note and example/exercise types
> fix note titles, make example & note styling consistent for baked books

- bower.json
updates coach to [coach-20170630.a](https://github.com/openstax/tutor-js/releases/tag/coach-20170630.a)
> update coach version to include exercises fix for the latest tutor api

- src/scripts/pages/donate/form/form-template.html
- src/scripts/pages/donate/form/form.coffee
- src/scripts/settings.js
This allows email in the donation submission form to be changed via `settings.js`.
The email address in the "TNE_Admin_Email" field needs to be changed to openstaxgiving@rice.edu as opposed to invoices@cnx.org.
Also, this is the fix for webview only, I will have another pull request in the cnx-deploy .
> Make donation email address configurable

- bower.json
- src/scripts/modules/media/body/_make-block.less
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/body/content-common.less
- src/scripts/modules/media/body/content-raw.less
- src/scripts/modules/media/body/content.less
- src/scripts/modules/media/header/header.less
- src/scripts/modules/media/tabs/contents/toc/section.less
- src/scripts/pages/donate/form/form-template.html
- src/scripts/pages/donate/form/form.coffee
- src/scripts/settings.js
if a user follows an inter-book link in baked content (i.e. Review Questions to Answer Key), the URL being navigated away from is not stored in browser history, yet two extra entries are stored in history, one being the long href with a hash (i.e. `#fs-id2197874-solution`), and one without a hash. Finally, the URL is canonicalized and updated, and stored in history. 
Example URL: 
```
/contents/185cbf87-c72e-48f5-b51e-f14f21b5eabd@10.61:a2d22c3d-7bba-5629-bb1a-a2e5eb375e0f@10.61#fs-id2197874-solution
```
User follows link, origin URL is stored, two intermediate URLs are not stored, final URL is stored. 
Back button now works reliably, but still stores extra URLs in the history. ~~Navbar hiding anchors is fixed.~~
This problem ended up being decently complicated. Backbone's `navigate` is …
> fix history issue, fix anchor link position - beware wall of text

- script/build
- script/setup
script/bootstrap has `source ~/.nvm/nvm.sh` which sets up the $PATH
environment variable.  That is how `npm` and `node` can be found.  This
works in script/bootstrap, but when it gets back to script/setup, $PATH
is not set up anymore and it cannot find `npm`.
On jenkins, we are seeing:
```
17:57:24 Now using node v6.9.1 (npm v3.10.8)
17:57:24 Using node: v6.9.1
17:57:25 Using npm: 3.10.8
17:57:25 ==> Installing package dependencies
17:57:25 ./script/setup: line 6: npm: command not found
```
---
Jenkins built successfully: https://jenkins.cnx.org:8080/job/Build_CNX_webview/255/ :tada:
> Fix scripts to get the nvm settings from script/bootstrap

- src/scripts/helpers/links.coffee
The 'this isn't the latest version click here" message uses an old url composed of bookid and page number. That doesn't survive crossing book versions w/ different numbers of pages (before the page in question). We're hitting this old bug more now, because going from unbaked -> baked will reliably add one or more pages to every single chapter.
> Don't use page number in links to other versions of book

- src/scripts/helpers/links.coffee
- src/scripts/modules/media/footer/metadata/metadata.coffee
- src/scripts/modules/media/latest/latest.coffee
- src/scripts/modules/media/media.coffee
This will now correctly set the `<link rel="canonical">` header to the value of the book uuid + page uuid, without versions, rather than just the book uuid for all pages. This is needed stop confusing Google and hypothes.is as to the correct URL to use for a given page.
> update canonical link for each page

- src/scripts/helpers/handlers/analytics.coffee
- src/scripts/loader.coffee
- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/tabs/contents/toc/page.coffee
- src/scripts/router.coffee
This changes the analytics code to support an array of analytics IDs rather than a single analytics ID.
The various call sites may be good candidates for cleaning up when exactly we send an analytics event.
One thing that might be worth including soon (maybe in a subsequent PR) is to fix when these analytics events are being fired. It might be worth spending time to write unit tests so they don't break in the future.
> add support for analytics array

- src/scripts/helpers/handlers/analytics.coffee
A bug was noticed in #1602 . This _should_ fix it (maybe?)
> fix sending analytics when no ids are present

- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/contents.less
for listing Books that a Page is in. This was introduced in #1606 but only worked for some browsers, and caused rendering problems in MS Edge (see #1610)
> remove the max-two-lines for Books that a Page is in

- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/media.less
- src/scripts/modules/media/title/title.less
changing mobile scrolling so that when scrolling down the entire header goes away, and then when scrolling back up the nav bar (contents button and title) comes back but you still have to scroll all the way to the top for the full header. Unless the toc is open then the nav bar and toc remain pinned Regular view remains unchanged
> Mobile scrolling

- src/scripts/modules/media/body/content-baked.less
Fix for #1633, apply centered text and remove bold.
> Support for .centered-text

- src/scripts/config.js
Upgrade MathJax to 2.7.4 and enable SRE for accessibility. MathJax was upgraded because the MathJax SRE extension doesn't exist for MathJax 2.6.1.
The [AssistiveMML](https://docs.mathjax.org/en/latest/options/extensions/assistive-mml.html) just exposes MathML to browsers that support reading it... it does not add human-readable alt-text... the [mathjax-sre.js](https://github.com/mathjax/MathJax-a11y/blob/master/docs/README.md#introduction) does that (adds human-readable text).
In order to include `mathjax-sre.js` we had to upgrade MathJax to 2.7
> Upgrade MathJax to 2.7.4 and enable SRE for accessibility

- src/scripts/models/content.coffee
- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/media.coffee
- src/scripts/modules/media/nav/nav.coffee
This defers sending Google Analytics until after the canonical URL is loaded into the browser.
The code assumes a couple of things:
- the browser URL is the canonical URL at the point when the `pageView` event is fired
- the `googleAnalytics` field is populated **before** the canonical URL is determined
(there is a persistent JSON parsing error in the screencap, but it's my machine, not a bug introduced in this code)
> send canonical URL to book analytics

- src/scripts/modules/media/body/body.coffee
Originally reported in https://openstax.slack.com/archives/C196UGS2C/p1529053670000358
Trackers on just a Page were not being sent. This PR includes the page tracker as well when submitting analytics.
- Page in a book with both having trackers set (it looks like it might be the same tracker): `/contents/r-QzKsl_@7.23:_97x1rAv@2/Introduction-to-Sociology`
- Page in a book with just the page having a tracker `/contents/FqtblkWY@2.1:pLGsuj0f@2/Przedmowa`
- Just a Page with a tracker `/contents/pLGsuj0f@2/Przedmowa`
- Just a Page with no tracker: `/contents/KvFTO2EG@2/Acknowledgements`
Full testing probably needs to include a Book with no page tracker and maybe a case where the book and page trackers are different (but both set)
Full testing probably also needs to check that clicking …
> include page analytics tracker

- src/scripts/modules/media/body/content-baked.less
solving #1681 
I've changed general rule for `span` with `data-type="media"` inside blockish elements. I didn't find any place in Biology book that would be affected badly with this change (all I did was change the direct child into the child attribute, because some of the QR have more containers than others).
> fixed distance between QR codes and content

- src/scripts/modules/media/body/content-baked.less
#1685 
fixed the mathjax styling so it should no longer affect elements outside of table
> changed the mathjax styling to target more specific elements

- src/scripts/modules/media/body/content-baked.less
#1636 I've breaking the line after every image that appears in the exercise.
> Fix improper text wrapping around exercise figures

- src/data/cms-books.json
- src/scripts/collections/featured-openstax-books.coffee
Fixes qa.cnx.org books pointing to cnx.org.
> Build the book urls instead of fetching them from the CMS

- src/scripts/collections/featured-openstax-books.coffee
- src/scripts/modules/featured-books/featured-books-partial.html
- src/scripts/modules/featured-books/featured-books.coffee
- src/scripts/modules/featured-books/featured-books.less
1) Clicking on a book cover opens in a new browser tab (links have to be relative for webview to do its magic)
2) ‘Show More’ link appears even for books that have no summary (a bootstrap style was colliding with my style named `show`)
> Fix bugs found in the webview home page during testing

- src/scripts/modules/media/body/content-baked.less
#1737 
`.os-figure` do not have margin top / bottom but they had `margin: 1rem 0;` inside of notes
> issue 1737 set the same margin for os figure inside and outside notes

- src/scripts/modules/media/body/content-baked.less
Scales down images in media objects with class `scale-down` to be 60% of the content width. Link: Issue #1709
> Support scale-down class on media objects

- src/scripts/models/contents/node.coffee
- test/scripts/helpers/handlebars/date.js
- test/scripts/models/contents/collection.js
- test/scripts/models/contents/page.js
Oops for the page extras url.
Date tests were always broken on OS X. I fixed them but the fix expected 2 digits, which does not work when the day is less than 10 (it does not prepend a 0).
> Fix URL for page extras; Also fix date tests on OS X when day < 10

- src/scripts/modules/media/body/content-baked.less
Issue : #1777 
I've changed display style of the paragraphs in exercises and solutions:
- the first paragraph displays `inline`, what's making number of the exercise to be inline,
- other elements are display as `block` like in pdf.
> Fixed incorrect display of lists

- src/scripts/modules/media/body/content-baked.less
#1814 
There are 3 points in this issue:
1. Number of table is inside of it.
2. This table in PDF is unnumbered.
3. Headers of the columns and figures inside the tabel are differently aligned.
Only `3` is webview related
This PR is fixing `3` by removing unnecessary margins around figures inside tables and setting padding-top for figure caption because it was overridden by styles for table caption (there is the same class for figure and table caption)
As you can see on screenshot there is wrong html markup for first figure caption (and probaby also for other ones?)
> issue-1814 fix displaying os-figures inside tables

- src/scripts/helpers/handlebars/trim.coffee
- test/scripts/helpers/handlebars/trim.js
- test/scripts/helpers/links.js
Test plan
=====
Story
-----
AAT, I'd like a webview test that asserts Unicode in URL is allowed
Steps
---
1. Visit:
https://qa.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2 
it redirects to:
https://qa.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2/123-Naprężenie-odkształcenie-i-moduł-sprężystości 
instead of:
https://qa.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2/123-Naprenie-odksztacenie-i-mo
2. Ie.: if the Unicode characters in the URL become stripped out (from the page title), this is a bug.
Expected result
----
- A URL with Unicode characters shows up complete in the address bar.
- Whitespace is replaced with dashes.
- Punctuation is stripped out (ie. question marks, exclamation marks)
> Do not strip non-ascii chars from url

- src/scripts/modules/search/search-template.html
- src/scripts/modules/search/search.coffee
- src/scripts/modules/search/search.less
#1703 
Hide filter column when loading and center progress bar. Also add some `margin-top` for header `Wyniki wyszukwiania` > `Search results`
> issue 1703 add aria-busy attribute to search view and modify design when searching

- Gruntfile.coffee
- package.json
To be served via the `gzip_static` nginx module. This prevents nginx from having to do work to compress these files every time the page is loaded. Original files are still present. Non-svg images are not compressed because they generally do not compress well. `require.js.map` is too small to compress but unfortunately grunt did not seem to have an easy way to filter files by size.
Goes with https://github.com/Connexions/cnx-deploy/pull/731
Output:
```
Running "compress:dist" (compress) task
Verifying property compress.dist exists in config...OK
Files: dist/fonts/FontAwesome.otf -> dist/fonts/FontAwesome.otf.gz
Files: dist/fonts/fontawesome-webfont.svg -> dist/fonts/fontawesome-webfont.svg.gz
Files: dist/fonts/fontawesome-webfont.ttf -> dist/fonts/fontawesome-webfont.ttf.gz
Files: …
```
> Gzip compressible dist files

- src/scripts/modules/media/body/content-baked.less
- src/scripts/modules/media/body/content-common.less
#1831, #1840 and #1843 
I removed old code from `content-common.less`. It was moved to `content-baked`. I also set padding left for all lists inside tables to be 1.5em
> issue 1831 / 1840 / 1843 - no padding left for lists inside tables

- Gruntfile.coffee
This PR excludes settings.js and require.js.map from being compressed.
settings.js is useless for deployment, because it is templated in Ansible, and devs might want to make local changes and have those be reflected in the local dev server
require.js.map is too small and becomes larger when compressed
Output:
```
Running "compress:dist" (compress) task
Verifying property compress.dist exists in config...OK
Files: dist/fonts/FontAwesome.otf -> dist/fonts/FontAwesome.otf.gz
Files: dist/fonts/fontawesome-webfont.svg -> dist/fonts/fontawesome-webfont.svg.gz
Files: dist/fonts/fontawesome-webfont.ttf -> dist/fonts/fontawesome-webfont.ttf.gz
Files: dist/index.html -> dist/index.html.gz
Files: dist/locale/en-US/dictionary.ftl -> dist/locale/en-US/dictionary.ftl.gz
Files: …
```
> Don't gzip settings.js and require.js.map

- src/scripts/modules/media/body/content-baked.less
Issue #1855, but originally it was created on `cnx-recipes` repo https://github.com/Connexions/cnx-recipes/issues/555.
I've simply changed display style for lists which are direcly below the problem (or solution) number. I've also deleted top margin to those lists in order to reduce the space between the number and first element of the list.
> Fixed lists' margin in exercises

- src/scripts/modules/media/body/content-baked.less
Numbering fixed in recipes https://github.com/Connexions/cnx-recipes/pull/565 and display is fixed in this PR.
Basically I've changed this commit https://github.com/Connexions/webview/commit/a1f00679b7910be449a2c7dc90b89e4577c5c461 to be more specific (in the `os-eoc` and in the `os-eob`, is that correct @PatBoj ?)
> fixed numbering and display of exercises

- src/scripts/modules/media/body/content-baked.less
> Fixed inconsistent displaying of headers of formulas

- src/scripts/modules/media/body/content-baked.less
#1868 
Do not override display setting for `notes` and set `margin-top: 0` when inside `os-problem/solution-container`
> add exception for notes to os-problem/solution-container

- src/scripts/models/content.coffee
#1897 
`@getPage(result).get('title')` for `unbaked` books was returning `Preface`
for `baked` books: `<span class="os-text">Preface</span>`
Regex before change: `match(/^Preface/)` `^` is checking if text starts with `Preface`
Regex after change: `match(/Preface/g)` is checking if text contains `Preface`
> issue 1897 change regex to match also baked books

- src/scripts/modules/media/footer/footer.coffee
#1883 
Check if `scrollY` has changed after opening tab and if so then return to starting position.
> issue 1883 stay at current scroll position after opening history tab

- src/scripts/modules/media/body/content-baked.less
#1910
According to changes in Connexions/cnx-recipes#613 - I removed the os-number paddings in exercises, so after merging 613 from recipes it will be fixed properly.
> removed paddings from os-number

- .jenkins/deploy
- Dockerfile
- conf/nginx.prod.conf
- conf/supervisord.prod.conf
- docker-compose.override.yml
This modification helps makes the container look and act more like production.
One can specify which type of runtime they'd like to use the container as by modifying the `ENVIRONMENT` environment variable. The environment can either be 'dev' or 'prod' to indicate whether the container should run in development mode or production mode. Development mode runs nginx from the source code, while the production mode runs from the dist (or built/compiled code).
> Modify the container to run the 'dist' version of the code

- src/index.html
Avoid `document.write()`. Prevents the console warning and might have performance benefits (probably negligible though) because the browser doesn't have to rebuild the DOM tree.
> Small trick to avoid document.write()

- src/scripts/models/content.coffee
When clicking on a featured book, the user should land on the first module page on all books.
issue #1897
> Remove isCcap requirement for pages results - issue #1897

- src/scripts/modules/media/footer/footer.less
#1882
There was additional `border` on `:focus` which was causing moving all table. This border is not needed because other elements does not have border so when it's added position of other elements have to be updated.
> issue 1882 remove border on focus

- src/scripts/models/featured-openstax-book.coffee
- src/scripts/modules/featured-books/featured-books-partial.html
- src/scripts/modules/featured-books/featured-books.coffee
- src/scripts/modules/featured-books/featured-books.less
#1905
There was few problems with this issue:
1. `description: $(data?.description).text()` was converting html description to only text. This is why `<a>` tags were missing - I've created `parseDescription(desc)` to remove all html tags from description except `<a>` tags.
2. `shave` module was converting desc to `text` so again all html tags were gone - I've replaced this module with css rule which is changing height of `.description` to `60px` or `auto` depends on click on `Show more / Show less`.
Now it looks and works the same as before but we are showing `<a>` tags from description.
> issue 1905 show links in book descriptions

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content-common.less
#1757 
To force screen readers to read a text after hiting `Show Solution` we need to have an empty element with `aria-live="polite / assertive"` and content of this element shoud get updated after click.
- To check if this is working go to http://localhost:8000/contents/mwjClAV_@7.1:0KhpF2RH@21/Real-Numbers-Algebra-Essentials
- Start screen reader (Ubuntu - Windows + Alt + S)
- Click before `Show solution` and hit Tab to navigate to button - hit eneter - wait for screen reader to read text
> issue 1757 read solution after open

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/modules/media/nav/nav-template.html
- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/modules/media/tabs/contents/toc/section.less
#1944 
1. Change `span.section-wrapper` to `<a>`
2. Add `aria-label="Click to Show the Table of Contents"` and translation to button `Contents`
I'm not sure about solution to `1`. Should I leave `span` and only add `<a>` or `<button>` for a ▼?
> issue 1944 add more accessibility to toc

- src/scripts/models/featured-openstax-book.coffee
#1964 
Replace end of paragraph (`</p>`) and `<br>` `<br/>` tags with space ` `. Also trim text to avoid double spaces.
Other tags like `<p>` `<span>` etc. are removed at the end.
Input:
`<p>abcd</p><p>1234 <a href="#">link</a><br>ghji</p>`
Output:
`abcd 1234 <a href="#">link</a> ghji`
> replace <br> and </p> tags with spaces

- src/scripts/modules/featured-books/featured-books-partial.html
- src/scripts/modules/featured-books/featured-books.coffee
- src/scripts/modules/featured-books/featured-books.less
#1970 #1971 
- remove some shave.js dependencies which are no longer in use
- add ellipsis (...) at the end of the line with some gradient effect
- hide `show more` button when description is short enough
Info: We couldn't use shave.js because this script was removing all html tags and we needed `<a>` tags from description.
> issues 1970 and 1971 - add ellipsis and remove .more button when desc is short enough

- .jenkins/deploy
Fix the "Publish Release" stage's condition by using [Jenkins' built-in conditions](https://jenkins.io/doc/book/pipeline/syntax/#built-in-conditions).
Move this to the last stage in the pipeline to prevent premature release.
This also fixes the container tag name by dropping the `v` prefix.
> Fix and move the publish release stage

- .jenkins/deploy
This brings things to a completely successful test run. We're filtering on these markers because the stack deployment at this time because the stack is missing components, which means we aren't able to run all the tests.
> Fix functional test execution to filter for stack deployment testing

- src/scripts/pages/app/app.less
#1896 
Issue was caused because Google Chrome Anchor Scrolling feature.
At every page change content of `<header id="header">` is rerendered which mean height of this element i jumping from `0` to `x`. When we change page for the first time it tooks longer time to load than next changes which mean view is scrolled before height of header was adjusted, so Google Chrome is trying to fix this with new feature called Anchor Scrolling. 
Fix is simple - disable anchor scrolling. However i'm not sure were should I put this css?
> issue 1896 disable overflow-anchor (Google Chrome anchor scrolling)

- src/scripts/modules/media/body/content-baked.less
I've deleted default markers from lists with `class="circled"` and I've also changed padding in those elements.
> Deletes default markers in circled class lists

- src/scripts/modules/media/body/content-baked.less
#2011 
`[data-align="center"]` should apply also for `<th>`, not only for `<td>`
> issue 2011 center text in all table cells with data-align=center

- src/scripts/pages/browse-content/browse-content-template.html
- src/scripts/pages/browse-content/browse-content.less
#2004 
add responsivity to `.browser-content`
I've change `ul, li` to `section` because those elements looks more like sections with headers, images and descriptions. I've also used flexbox to postion those elements so there shouldn't be any problems with responsivity.
> issue 2004 add responsivity to browser-content

- src/scripts/modules/media/nav/nav.coffee
- src/scripts/modules/media/tabs/contents/contents-template.html
- src/scripts/modules/media/tabs/contents/toc/section-template.html
- src/scripts/modules/media/tabs/contents/toc/section.coffee
#1944 
[There were added multiple commits to previous version so I recreated changes on new branch]
Previous version worked only in incognito mode and weird things were happening in normal mode.
Changes:
Remove aria-live and role="alert" attributes from .toc and set focus() for closest link or button instead.
In .toc there are: button.section-wrapper for collapsing sections of modules and .name-wrapper a for individual module. I'm selecting first of those two with querySelector which is forcing ChromeVox to read exactly this text.
> issue 1944 rewrite accessibility support for links inside toc

- src/scripts/modules/media/body/body.coffee
- src/scripts/modules/media/body/content-common.less
#1999
[There were added multiple commits to previous version so I recreated changes on new branch]
overflow: auto; for [data-type="equation"] which makes blockish equations scrollable on smaller screens.
Wrap tables inside unbaked books with additional div so we can apply overflow-x: auto to them which makes them scrollable for devices with smaller screens.
> Issue 1999v2

- src/scripts/modules/media/footer/metadata/metadata.less
#2000 
When sidebar is open the content is compressed too much even on larger resolutions, so I've added same responsivity rules for this case.
> issue 2000 add responsivity rules for metadata when sidebar is open

- src/scripts/modules/splash/splash.less
#2006 
move text on splash screen a little bit higher at smaller resolutions
> issue 2006 move text on splash screen a little bit higher at smaller resolutions

- .jenkins/deploy
This refactors the Jenkins functional test stage to use the library function,
which is basically the same code here. The only addition is that the library
code notifies slack when there are failures.
> Replace the functional test stage with the library function

- src/scripts/modules/search/results/filter/filter.less
#2028 
`dd` elements (counters next to dates and authors names) had hardcoded style `margin-left: 180px` which was causing overlapping text. I've positioned thoses elements with flexbox so they look the same but doesn't have hardcoded values.
> issue 2028 add responsivity to search results filters

- src/scripts/modules/splash/splash.less
#2006 
It seems like Firefox and Google Chrome were calculating differently position and height of `relative` elements so I've rewrote this part. There are screenshots in issue conversation and you can also check previous version at `qa.cnx.org`.
> issue 2006 fix resposivity issue between firefox and chrome for splash text

- script/build
These were not being included in the built package, as seen by the containerized deployments.
Context: https://openstax.slack.com/archives/C0LA54Q5C/p1542224114647800
> include fonts in the build

- src/scripts/modules/media/body/content-baked.less
Continuation of the https://github.com/Connexions/cnx-recipes/issues/704 and it will be working with this PR https://github.com/Connexions/cnx-recipes/pull/718. I've deleted automatic numbering in lists with `class="stepwise"` and changed left padding.
> Delete webview numbering in stepwise lists

- src/scripts/modules/window-with-sidebar/window-with-sidebar.less
#2064 
This issue was occuring only in firefox because of asynchronus scrolling https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects
It seems to be fixed after adding `position: sticky;` (which mdn mentions in link above) to the `.sidebar` which is container of element which has `position: fixed;`
`position: sticky;` "force" browser to adjust position of this element synchronously.
> issue 2064 fix for firefox issue with scroll linked effects

- src/scripts/modules/media/nav/nav.coffee
#2056 
Remove `clear search` icon (x) when user manually deleted text in search input.
I've changed `keydown` listener to `keyup` because text is deleted whe key is up and not when key is down. It will not affect other operations like inserting text or hitting enter.
> issue 2056 do not show clear search icon (x) because it's confusing

- Jenkinsfile
This is a hack to restart a service, because docker service doesn't support
single service restart. So we scale to zero and then back to one.
This is the community's best solution to the problem.
> Restart the http-cache on deploy

- src/scripts/modules/media/body/content-baked.less
#2087 
apply the same padding to `<th>` and `<td>`
> issue 2087 apply the same padding to <th> and <td>

- src/scripts/modules/media/body/content-baked.less
https://github.com/Connexions/webview/issues/2097
After removing paddings of `p`, `ul`, `ol` and `.os-table` the solutions for Examples look fine to me.
I'm not sure if that should be removed only for `examples` or also as is now for `notes` and `exercises`?
> removed paddings from p, ul, ol and .os-table in show solution area

- src/scripts/modules/media/body/content-baked.less
#2127 
Remove all styling for `.stepwise` lists until recipies part will be applied to all books.
See #2095 for details
> Remove all styling for .stepwise lists

- src/scripts/modules/media/body/content-baked.less
@PatBoj pr https://github.com/Connexions/cnx-recipes/pull/750 was merged so now we can apply styles for `.os-stepwise`
This style was removed due to style breaking in books which wasn't baked with proper recipies / feature flag (https://github.com/Connexions/webview/pull/2138)
> Style .os-stepwise

- src/scripts/modules/media/footer/downloads/downloads.coffee
Events added for Google Analytics were preventing the events of the download tab parent object from firing when the button was clicked. The fix was to combine all the events. Many thanks to Roy for the path to the fix.
> Fixed event issue

- src/scripts/models/content.coffee
- src/scripts/models/contents/collection.coffee
Check the length of the pages array and return an empty string for empty contents to prevent an error.
> Stop throwing an error when collection is empty

- src/scripts/modules/media/body/content-baked.less
Width of 100% was overriding the width in the HTML. Removing it allows the sims to display correctly.
> Allow sims to use width specified in markup

- src/scripts/modules/media/body/content-baked.less
https://github.com/openstax/webview/issues/2201
Changed display of `first paragraph` inside `problem` in `exercises` to be `inline-block` in order to get rid of line break before mathjax elements in Safari browser.
> fixed line break before math elements in safari browser

- src/scripts/modules/media/body/content-baked.less
In https://github.com/openstax/cnx-recipes/pull/940 list in abstract in Calculus is changed by recipes to numbered list. That how it looks at this moment:
In this PR I removed additional bullet list and I changed the left padding.
> Remove bullet list from abstract

- src/scripts/modules/media/body/content-common.less
This PR will solve:
https://github.com/openstax/webview/issues/2154
https://github.com/openstax/webview/issues/2183
https://github.com/openstax/webview/issues/2184
It will also affect any other content that is created in tables eg `tables with equations`. 
https://katalyst01.cnx.org/contents/mwjClAV_@8.2:SXjiAlpU@8.2/Key-Equations
@openstaxalina This should look good also for tables with merged cells, paddings in cells also look good. It will be verified by QA.
I was thinking if we should make the `table head` border darker or thicker so it can be distinguished from the table body?
> changed default table styles

- src/scripts/modules/featured-books/featured-books-partial.html
We are setting the `data-bypass` attribute on the anchor to allow the default
behavior to proceed. This passes the requested link to the browser rather
than having the javascript capture it for internal requesting of new content.
We make the browser do a request of these URLs so that it contacts
the webserver (nginx) to do redirects of REX books (aka all openstax books).
This is associated with openstax/cnx#401
> Do a hard request for featured book clicks

- src/locale/en-US/dictionary.ftl
- src/locale/pl/dictionary.ftl
- src/scripts/modules/footer/footer-template.html
- src/scripts/modules/footer/footer.coffee
- src/scripts/modules/footer/footer.less
The Android app was removed from the Google Play Store so the link in the footer no longer works.
> Removed link to Android app
